### ISSUE TITLE
Onboarding Responsiveness

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#101]

**Comment by laurenluz** [comment]
What is "onboarding"? I don't know how to test this.

**Comment by MoeNick** [comment]
@laurenluz if you have no completed profile (email / name not provided) you'll be asked to go to a 3 step wizard to provide more information upload a photo and create a profile, this wizard is called "Onboarding" we should test whether it looks good on mobile and small screens or not.

**Comment by MoeNick** [comment]
@Cotabe Dan I just assigned it to you to get more familiar with the flow.

**Comment by Cotabe** [comment]
Awesome thanks @MoeNick

**Comment by Cotabe** [comment]
@MoeNick  I went through the flow... it is very clear and simple congrats @MohammadPCh !!

On the computer, I would only suggest changing the color of the notification text (more contrast). I almost missed it.

And for the mobile:

- On my account page, it does look a bit awkward. Maybe have the text box in front of the profile pic to make the message and the words more visible.
![IMG_4041.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/e28b8f95-2892-4f2b-b064-a006f391a9b2)

- On the complete profile pop-up. Minor thing... I would recommend having the text aligned to the centered

- I suggest that on Fancy profile photo it says "upload from device" instead of from computer.

- Final text is behind my Torus wallet.
![IMG_4042.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/c7a1510b-7f9d-4851-b323-f9bbe90e340e)

**Comment by MoeNick** [comment]
Thanks @ascode94 

@Cotabe would you please check it out again?

**Comment by Cotabe** [comment]
@MoeNick 

Looks good now :)
