### ISSUE TITLE
Filtering/Sorting

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1121]
@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/658)

![Screen Shot 2022-07-12 at 3.50.16 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fa49cb5e-99f2-4547-a87b-f9d64920e4d1)

## Design resource
Filter/sort module -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11069%3A199976)

**Note:**
The filter and sorting module should work both on the categories and search results.
---

**Comment by divine-comedian** [comment]
Looking at the current filter views there's a few things that don't quite make sense to me.

As a user from the four filter options presented if I select GivingBlock and Accepts GIV token will always yield no results. We could assume any project that isn't a giving block project would accept GIV tokens at the moment, right? 

The Giving Block also already has its own sub category under non-profit so having this as a filter might seem redundant. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184698538-446c7d14-b4b6-443c-82f8-82261dceafcd.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184698595-26ac77a3-a250-4728-ba54-3421d12254c3.png">


we should also consider removing "from Trace" since Giveth Trace is no longer maintained. 

The user should have the ability to 'clear filters'

maybe some suggestions for different filters:

`Has updates` (the project has at least 1 update)
OR 
`Recently Updated` (where we define recent as < 3 months)

perhaps also a 'least funded' option for the sort.

**Comment by MoeNick** [comment]
- [ ] we should also consider removing "from Trace" since Giveth Trace is no longer maintained. 

- [ ] The user should have the ability to 'clear filters' - I'm also thinking like that, @mosaeedi can you take a look? 

@divine-comedian for your suggestion, due to it might have spec changes, I'll put them in another issue, let's focus on functionality in this step.

**Comment by MoeNick** [comment]
Unfortunately givingblock has different labels on staging and I can say also in production, so we can't rely on that fact.  @divine-comedian

**Comment by divine-comedian** [comment]
> Unfortunately givingblock has different labels on staging and I can say also in production, so we can't rely on that fact. @divine-comedian

but why is there a giving block filter and a giving block sub category? this seems redundant.

**Comment by maryjaf** [comment]
@MoeNick 
1-"Apply" & "clear" isnot shown despite being shown in Figma, this is ok?
2- Sort by options should be displayed in the filter counter?
That is, if it is sort by "newest" and a "verified"from Project features is applied
Counter "2 "should be displayed on the filter (in Figma, it looks like this)
But in the test environment 1 is displayed (Only Project features are counted)

**Comment by alireza-sharifpour** [comment]
@maryjaf @MoeNick New Sorting And Filter design is ready for test.

**Comment by maryjaf** [comment]
I did not see the new design figma.
In the new design in test env , there isn't " APPLY"option, and in fact, the changes are applied by selecting a filter
And in the window that opens, we see the "ClEAR ALL FILTER" option only , the filters window can be closed only by selecting  close icon after applying the filter
It may not be a good user experience
It is approved by you? @MoeNick 

But in general, no technical problems were observed in filtering and sorting, thanks @alireza-sharifpour

**Comment by maryjaf** [comment]
Please check this scenario:

- A main category is selected
- Filtering and sorting have not been applied
- By selecting the main category, one of the projects of this main category will be displayed, but there are more projects for this category(Pic-1)
- By selecting a subcategory, more projects will be displayed(pic-2)
- And if in this case the main category without sub is selected again, all projects will be displayed(pic-3)

This problem does not always occur
@alireza-sharifpour @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/5549d910-4c45-409b-af0c-0f7babcc6560)

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/02214fe7-0420-40da-8f20-57571cab5616)

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/95f464d4-20ad-47bc-ac3d-6d2b75c46142)

**Comment by alireza-sharifpour** [comment]
> I did not see the new design figma. In the new design in test env , there isn't " APPLY"option, and in fact, the changes are applied by selecting a filter And in the window that opens, we see the "ClEAR ALL FILTER" option only , the filters window can be closed only by selecting close icon after applying the filter It may not be a good user experience It is approved by you? @MoeNick

It's the latest design, i think we need to clear old designs so the latest one be more clear @mosaeedi @MoeNick

**Comment by alireza-sharifpour** [comment]
> 

Thanks @maryjaf for testing, it's weird!
I tested it and i couldn’t reproduce the bug that you mentioned, is it possible for you to install [React Dev Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) and check here and send an screenshot when there is a problem here? 
When you install React Dev Tools you will have new section in the Chrome Dev Tools:
![Screen Shot 2022-09-08 at 1 04 29 PM](https://user-images.githubusercontent.com/48887817/189075566-550f460f-b6b4-4325-a202-2db62217e458.png)

In here please select React Context, then Select ProjectsContext from the menu, there you can see this picture:

![Screen Shot 2022-09-08 at 1 05 42 PM](https://user-images.githubusercontent.com/48887817/189075806-918321c3-97c6-4e56-a044-40e0e65bd685.png)
The variables are the things that we are sending to backend and getting the result, if we have them we can figure out what the problem is.

Feel free to DM me other devs if there is a problem.

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour 
This scenario happens when you select a main category for the first time.

**Comment by MoeNick** [comment]
@maryjaf ut's waiting for your confirmation.

**Comment by maryjaf** [comment]
thanks @alireza-sharifpour 
The last bug is fixed
