### ISSUE TITLE
Project single page: Search inside donation list is not working 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#113]

**Comment by CarlosQ96** [comment]
@MoeNick Just FYI will be adding search functionality by donator name.

**Comment by MoeNick** [comment]
I can't search by token name, address or amount. I only can view results on Donors name, correct?

**Comment by CarlosQ96** [comment]
I added support for ordering results by amount, usd, created at desc/asc. And the donors name search. 
I validated with Pedro. But let me know if another search is required.

**Comment by CarlosQ96** [comment]
And it would be search by exact address right?

**Comment by laurenluz** [comment]
search is working now.... only "anonymous" is not anonymous... when I search for Ramin's name, it shows me his anonymous donation:

@CarlosQ96 please make it so that "anonymous" is actually anonymous 😅 

![image](https://user-images.githubusercontent.com/75490971/159960393-88e4f61d-48e0-4e13-baa0-b39a13070385.png)

**Comment by laurenluz** [comment]
looks like it's working now on develop!

![image](https://user-images.githubusercontent.com/75490971/160176732-425d2f1f-a0d9-46ea-8fb6-3cd18d75ca44.png)
