### ISSUE TITLE
GIVpower APR distro

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1183]
I locked 10,000 testGIV for 26 rounds. The APR was 3446,35%. I should have gotten a distro of 344,635 testGIV. But after they unlocked I only had 216.5 testGIV on my rewards.

Not sure if this is because the rounds are being considered 5min, but the farm time is normal or why? I wasn't able to check the amount locked on the contract either on blockscout.

**Comment by laurenluz** [comment]
@Cotabe I don't quite understand the issue you're describing...

You would have maintained the APR of 3446% for a full year in order to earn 344,600 GIV. You wouldn't have earned that in just a few minutes...

Just because the rounds are 5 minutes doesn't mean that the dApp considers 5 minutes to be equal to 2 weeks.

It just means that your tokens are unlocked after 5 min x 26 rounds... and that after that time, the APR goes back down.

Does that make sense?

**Comment by Cotabe** [comment]
Yes @laurenluz 

That was my main question. I just prefer not to assume anything.

I would love to check the APR with my spreadsheet. But not sure how to see the locked rewards on blockscout. 

@aminlatifi can you guide me through that?

**Comment by aminlatifi** [comment]
@Cotabe In order to see how much you have locked and your locked position one by one, run the below query here https://api.thegraph.com/subgraphs/name/aminlatifi/givpower-deployment-six

```
{
  user(id: "<YOUR_ADDRESS_LOWERCASE>") {
    givLocked
  }

  tokenLocks(
    where: {
      user: "<YOUR_ADDRESS_LOWERCASE>"
      unlocked: false
    }
  ) {
    amount
    rounds
    unlockableAt
    unlocked
    unlockedAt
  }
}

```

Change <YOUR_ADDRESS_LOWERCASE> with your lowercase address. Note, all values are in wei.

**Comment by maryjaf** [comment]
> @Cotabe is your issue resolved or does it need more testing?

@Cotabe
