### ISSUE TITLE
Bridging tokens for GIVpower

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1226]
Ask me details!

**Comment by laurenluz** [comment]
So when the user is connected to Mainnet they should see the GIVpower card, but actually they will not be able to stake on mainnet.

In order to stake, they must bridge to mainnet.

So we want to have it so that when the user is connected to mainnet and they click "stake", they get a modal that says...

"GIV staking is available on Gnosis Chain. Please bridge your GIV to Gnosis Chain, then switch network and stake to earn rewards."
Button: "Bridge your GIV"

That button opens the omnibridge in a new tab... also, when the user clicks it... they get a new modal that says...

"After you have successfully bridged your GIV to Gnosis Chain, switch network & stake for GIVpower!"
Button: "Switch Network"

**Comment by mosaeedi** [comment]
Note to Devs!

We are going to show only one modal instead of showing two modals.
But we cover both scenarios and let users either open the Omnibridge or Switch networks from the same modal.

![Screen Shot 2022-07-28 at 1.18.39 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/01df826b-b430-4d65-9966-5aaa4883c406)

## Design resource
The modal on Figma -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11877%3A208563)

**Comment by laurenluz** [comment]
@MohammadPCh Can you implement?

When on mainnet, the user should see the GIVpower staking card... but when they click "stake" they get this modal.

The bridge your GIV button should open the omnibridge in a new tab --> https://omni.gnosischain.com/bridge ... This action should not close the modal on the original page.
The switch network button should switch to gnosis chain & close the modal.

**Comment by MohammadPCh** [comment]
@laurenluz sure :)

**Comment by MohammadPCh** [comment]
@laurenluz @mosaeedi 
I have some questions:
1. should we show the GIVpower card instead the regular card?
2. should we show the apr on gnosis or apr on the mainnet? if we show the apr on gnosis may users be confused about it and think they will receive this apr with the current staked amount on mainnet.
3. if users don't have GIV on the mainnet all buttons are disabled and can't go to the stake modal and find the `get more GIV` link. I think it's the same problem for users on gnosis. (maybe the solution is to enable the stake button always).
4. what should we do with the `Increase your reward` button?  
5. should we show the user info (GIV stakes, unstacked, reward, ...) on gnosis or mainnet?

Thanks.

**Comment by laurenluz** [comment]
Hey Cherik

1. When GIVpower goes out, we will replace the regular card w/ GIVpower and discontinue mainnet rewards
2. I was thinking to show the APR on Gnosis... maybe we should add a tooltip or something saying that that's what it is... what do you think?
3. I think it would be great to enable the mainnet stake button if the user on mainnet has mainnet GIV in their wallet
4. Increate your reward should be grey
5. show the user info I think only on gnosis where it will be true. does that makes sense?

**Comment by WhyldWanderer** [comment]
Here is the modal
![image](https://user-images.githubusercontent.com/74267818/182909455-512fa449-6bdb-44ca-b257-53c7ac78ef08.png)

Links are working!

Here is the card when I am connected to Kovan (Mainnet)
![image](https://user-images.githubusercontent.com/74267818/182909635-0628d6a1-d055-4d30-a517-4e8eb984fdd6.png)


And here is the card after I have switched to Gnosis
![image](https://user-images.githubusercontent.com/74267818/182909741-c1f34a25-2d83-4b5a-8219-e9e2fc99ab23.png)


I dont see anything that explains the APR... but maybe it was decided that this wasnt needed. 
From what I can tell, this issue is fixed.

**Comment by laurenluz** [comment]
this is great!! thanks @WhyldWanderer @MohammadPCh

**Comment by MoeNick** [comment]
@laurenluz its unit test passed, so I put it back to unit testing, waiting to be merged on Giveconomy branch, then we can put it in UAT.

**Comment by laurenluz** [comment]
Hey @MoeNick - so unit test is when it is passed in the GIVpower test deployment... and then we move to done one things are merged to production?
