### ISSUE TITLE
GIVPower- Giveth Icon Button w/ Rewards 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1314]
Doing testing and as a newbie i had no idea what that icon with 1000 beside it meant....

Because i know about Web 3 (this is already more than some people know) I checked explorer and found out it was DRGIV2 toen

This was definitely not intuitive or an easy user experience

Recommendation 

- put DRGIV2 besdie 1000 token reward so people know what it is 
- put (?) icon so people that are confused what DRGIV2 is can find out more and understand it 

<img width="339" alt="Screen Shot 2022-08-04 at 21 09 34" src="https://user-images.githubusercontent.com/110338123/182934108-431d23ec-4fe7-4905-a8e4-27757f4fd0f0.png">

**Comment by laurenluz** [comment]
Well DRGIV2 is a token only used by our team for testing. I don't think adding that info in there really makes sense from a design standpoint, because it will never be shown on production. The GIV token logo is right next to it... indicating that it is your balance of GIV tokens.

Is that really unclear to you?
