### ISSUE TITLE
GIVPower- show locked GIV when unstaking (what's unavailable to remove) 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1320]
Under "unstake" it shows 100 GIV so i expected to remove it all but when i went to unstake it only showed 75 available (25 was missing)...I think an explanation of 25 locked GIV would be important here

Somebody might've locked ages ago and not be able to remember why the 25 is "Missing" 

I would add something like "Locked GIVPower" 25 or something like that right underneath "available to unstake"

<img width="1206" alt="Screen Shot 2022-08-04 at 21 37 56" src="https://user-images.githubusercontent.com/110338123/182938463-bd8a0752-8fa0-4d92-91ca-0c8cedfc4d60.png">

**Comment by laurenluz** [comment]
@mosaeedi What do you think about adding "Locked GIV" as a line between "Available to unstake" and "Total staked" as suggested by @tropicalmangos ?

![image](https://user-images.githubusercontent.com/75490971/192636531-84766caf-d739-4f36-835d-8e808113f405.png)

@tropicalmangos project earnings... I don't think this is a good idea, it will add a lot more information to a modal that already has a lot of information and it will be a completely way-off estimate. You could say "projected earnings if you kept the same staking amount staked for an entire year and the APR didn't change"... but you know, it would be totally different that what you actually I get. I think because the discrepency is huge, and the clutter is already there, I would prefer not to add it. Open to rebuttle though.
