### ISSUE TITLE
Show all GIVfarm cards when the user is connected to either network

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1356]
As we plan to end certain programs in the GIVfarm, we want to make it easy for users who withdraw liquidity from one place (e.g. GIV/xDAI on gnosis chain) to put it in another (e.g. GIV/ETH on balancer)

To do that, it would be nice to see all active farms within the same view (and let the user see the APRs) no matter what network they are connected to.

We have also made it technically possible to show farm cards on either network with either APR, what we need is a way to organize them clearly, and have an easy flow for bridging.

For example, if the user is connected to mainnet & wants to click on a gnosis chain card, they get a modal similar to this one for GIVpower. We would need to change the copy.

This needs a bit of advice process & design, so tagging @mosaeedi @divine-comedian and @MohammadPCh to discuss. If we can get a quick solution up before the GIVfarm changed on August 19, it would be idea.

FYI @moenick

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d62fe5f5-9f2f-4daa-903f-35e3cb4084ec)

**Comment by mosaeedi** [comment]
![Screen Shot 2022-08-15 at 7 21 50 PM](https://user-images.githubusercontent.com/13708322/184674501-31e0832b-0a7e-4db9-82d8-47cfa253f821.png)


## Design resource
Showing farm card for both networks -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12493%3A231529)


Important!
We have to group the farm card for the same network and show the network so users can see which card is related to which network. 
But when users are on a specific network, we don't need to show the network title then.

![Screen Shot 2022-08-15 at 7 23 35 PM](https://user-images.githubusercontent.com/13708322/184675204-48653d80-88ca-4bd7-ab0a-bb5f13f361d4.png)

**Comment by divine-comedian** [comment]
talking to @mosaeedi a bit earlier today I wanted to capture some of my feedback in the issue here -

looking at how some other platforms show their farms I think we can glean some ideas.

### ribbon.finance:
![image](https://user-images.githubusercontent.com/67759413/184715863-e97d5441-5652-406f-908c-b8069e4b24c2.png)


Having instead the network indicator inside of the farm card instead of a header. Assuming we'll have no farms on Gnosis Chain except GIVpower in 4 weeks and only Angel Vault and Balancer on mainnet it would actually look pretty empty and sad these separate views by chain. Also to mention we already decided we need to show the GIVpower card on both mainnet and Gnosis Chain.

**Comment by mosaeedi** [comment]
I hide my comments to prevent any misunderstanding.

**Comment by mosaeedi** [comment]
Here is the new design for showing all farms.

**Comment by MohammadPCh** [comment]
Thanks, @mosaeedi, I will talk with you, and ask some questions :)

**Comment by laurenluz** [comment]
This is working on production!
