### ISSUE TITLE
Verification form: let the User know the mandatory updates. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1364]
Add information to the verification form that indicates that quarterly updates are required to maintain verified status.

**Comment by MoeNick** [comment]
@NikolaCreatrix can you make it clear in which step and in what "copy" we have to change the flow about mandatory design in verification form?

**Comment by NikolaCreatrix** [comment]
@MoeNick so after our little discord 3some chat:) with Carlos, do you still need more clarity?

**Comment by MoeNick** [comment]
@NikolaCreatrix this is related to another task, in the verification form, as you see @WhyldWanderer asked to let the user know the rules of keeping the project updated before they apply for verification. 
My question is, where and which "content" should change in verification forms?

**Comment by NikolaCreatrix** [comment]
![mandatory updates before you get verified](https://user-images.githubusercontent.com/100084867/189902369-bf66abf8-1e28-4e68-a89d-7be3ce22aa76.png)

In the selected section - see picture, please paste this sentence:

"On the other hand, you will be required to post regular updates about your project, otherwise your verified badge could be revoked after 3 months of no updates."

Sounds good @MoeNick and @WhyldWanderer ? :)

**Comment by MoeNick** [comment]
@mateodaza ABOVE pls see the instructions :) ^^

**Comment by MoeNick** [comment]
@maryjaf please take a look.

**Comment by maryjaf** [comment]
this sentence was added
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/44e355ec-c9a1-4aea-b16d-3388e83042ec)
