### ISSUE TITLE
Standardized Project Format (Template)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1374]
About Us 
Mission 
Gallery 
Social LInks / Web LInks  :)
Ask 
Updates

**Comment by MoeNick** [comment]
- [ ] Project creation page: The project's Story should be split. 
- About Us
- Mission
- Gallery and video, upload/share links 
- Social Links / Web LInks :)
- Ask (how much funding are they looking to receive/ funding goal)

Do they have to be required? or optional.

- [ ] Edit projects

- [ ] Single project View | Public


- [ ] Single project View | Project Owner View

**Comment by MoeNick** [comment]
Thanks @tropicalmangos it's perfect, I'm ok with the concept, we have to gather all feedback and let it happen :)
However, my question above about backward compatibility is still not solved, what to do with the old and existing projects? how we can fill the content with a new format? what the onboarding flow is look like to convince them to provide more information? how they got there?

**Comment by mhmdksh** [comment]
> @mhmdksh same as we chatted about before. We do a phased approach:
> 
>     * communicate out to existing projects new rollout and ask them to fill projects via email, socials etc
> 
>     * reminders etc
> 
>     * for onboarding flow to make it easier I've put in guidelines and examples they can follow. Also we can remind them that projects with a complete profile (more pictures, better descriptions etc)get more funding
> 
>     * we can also create filler text for those projects that don't get filled out

Whoaaaahhhh???

**Comment by ahmadabugosh** [comment]
Hey @MoeNick for this I think your main concern was that it would be hard to add more fields to projects since most projects don't have those fields. I was thinking there are maybe 3 solutions to this:

1) Option 1, is we have it where if that field is blank it doesn't show up. For example, if there is no social link, impact stats, about us, year founded etc. it just doesn't appear (it will look like the current design). I think for that approach you may need to use components etc. to hide things if they are empty. 

2) The second option would be to have 2 project templates a new one and an old one, and people can upgrade to the new one if they fill in all the fields (maybe there is a prompt to upgrade and it makes them input all of the mandatory fields). 

3) The third option could be to do this in phases. For example, maybe to start we only include a few fields (like social links) and update the project page in a phased approach (with help from the community team to fill in all the project details we have and fill more as we go). 

Which of those 3 do you think is the most realistic to do?

**Comment by clara-zi** [comment]
> Notes from comms call:
> 
> @WhyldWanderer maybe we can add percentage completion? with a popup when projects login?
> 
> @SnakeGH says donors would like to see more interaction and proof of donations to the project. Metrics highly requested (what is the impact of funds donated)?
> 
> @tropicalmangos chat functionality to interact with projects? can be basic - leave name and email and project will get back to you or FAQ based.
> 
> Recommended basics for projects to have (from @tropicalmangos ):
> 
> * brief about the project
> * gallery /photos/ videos - showcasing impact (on the ground work/ communities impacted etc)
> * links (social, website etc) - adds legimitacy
> * project updates
> * metrics
> 
> @MoeNick what would be reasonable from a dev perspective?

From the donors survey (@SnakeGH) Donors would like to view projects by country: ideally on a map that could be zoomed in and out.

Could be good to start with a standardised location drop-down - that projects could select for their main country of operation.

**Comment by MoeNick** [comment]
Hey we finally have a prototype design 
https://forum.giveth.io/t/improving-single-project-screen/983
 please have you comments there/
