### ISSUE TITLE
No way to exit GIVdrop "claim" pop-ups

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#1402]
Is it supposed to be the case that there is no way to exit the pop-up window series for claiming GIVdrop? I want to close out of it, but it's impossible.

![image.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/4cbbc6e6-e5c0-4a91-b365-5ab8acd0a5e6)

**Comment by MoeNick** [comment]
@MohammadPCh @aminlatifi can you take a look?

**Comment by MohammadPCh** [comment]
Thanks, @danelsuga for reporting this. I think the design guys can help us because the UX is based on what we have on Figma.
but the UI is weird(sticking the text to the top). I tested it on my computer and It's ok, could you please share more info ( your browser and your screen size) that help me to reproduce it?

**Comment by danelsuga** [comment]
I'm on Chrome with a 11" inch screen.
