### ISSUE TITLE
logout with expired token

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#1436]
Nothing happens when the user token is expired and the user tries to log out.

**Comment by maryjaf** [comment]
How long is the lifetime of the token, and with this issue, what do we expect to happen after the token expires?
There was no figma on the task
@MohammadPCh @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> How long is the lifetime of the token, and with this issue, what do we expect to happen after the token expires? There was no figma on the task @MohammadPCh @alireza-sharifpour

Backend Guys know the exact Expiration time @mohammadranjbarz @CarlosQ96 
the issue was when we wanted to logout with invalid or expired token, the logout function didn’t work, because the token was not valid, so we couldn’t sign the user out.
know the issue is fixed.
for testing you can sign in and then change the token in localStorage or remove one or two letter from the end of it to make it invalid, after that you should be able to logout from the header menu.
@maryjaf

**Comment by maryjaf** [comment]
I tested this scenario in staging and it passed
sign in
change and invalid my token from inspect-local storage
go to my account page
tap on sign out 
and i signed out correctly
