### ISSUE TITLE
GIVpower - Locked GIV details table header font

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1512]
testing on https://givpower.vercel.app/givfarm

the text on this header is all misaligned - the size or styling should be fixed

also the `?` on the bottom seems to be top aligned when it should be center aligned with the text in front of it, not slightly above it.

![image](https://user-images.githubusercontent.com/67759413/190694907-082f9dd7-5790-4584-b58b-18d5c24010af.png)

**Comment by laurenluz** [comment]
on GIVeconomy test deployment, the alignment of headers is correct. Also the tooltip "?"s are both vertically aligned.

![image](https://user-images.githubusercontent.com/75490971/192634928-d4a14c21-0396-415f-9795-d73ab56787f5.png)

on GIVpower test deployment, I can't test it because the APR is 0 and I and not able to access the lockup details modal at all.

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks , I also tested it on givpower and I think it's fixed now.
