### ISSUE TITLE
Homepage text fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#153]
![image](https://user-images.githubusercontent.com/74267818/157294780-8a0151b1-3b0b-4e00-94c7-e397618b81c0.png)

Should say "Welcome to the Future of Giving!"

'Future of Giving' should always be capitalized this way.
Add an exclamation point.

**Comment by WhyldWanderer** [comment]
![image](https://user-images.githubusercontent.com/74267818/157334582-d259b271-0de6-4b06-9a31-be9951ee08a0.png)

Should say "Establish your project on Giveth to tap into the revolutionary funding opportunities of the Ethereum Ecosystem. Start raising funds within minutes. Creating a project is absolutely free!"

**Comment by WhyldWanderer** [comment]
![image](https://user-images.githubusercontent.com/74267818/157335724-29f43e78-5b79-447b-960f-cc8be0aab152.png)

'Project' should be with a lower-case 'p' in this sentence.

**Comment by laurenluz** [comment]
Ashley's fixes are great. Here are a few more:

![image](https://user-images.githubusercontent.com/75490971/158229387-ec5e01c5-7f81-4fd8-a458-76717472e3e1.png)

"Get rewarded for giving to for-good projects with zero added fees."

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/158229987-f9f541e9-9c16-4068-bfb4-e841ad8e7e68.png)

![image](https://user-images.githubusercontent.com/75490971/158233302-e3895fa1-cefd-4ca6-bac6-2a46f045869b.png)

The GIVeconomy
"Welcome to a future where we revolutionize economic systems, regenerate the Earth, evolve human coordination & create societies based on decentralization, freedom, community and love."

For Givers
"For the first time ever, there is an upside to donating. When you donate crypto to verified projects, you get rewarded with GIV from our GIVbacks program. Enjoy liquid GIV and a GIV/week flowrate from the GIVstream until 2026."

For Projects
"Create a project within minutes and start raising funds in crypto with zero added fees. Get verified and your donors will be rewarded by GIVbacks."

**Switch Projects & Givers so that Givers comes first.**

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/158233744-743ec778-cbf2-4470-bf56-83f59affcd15.png)

"Encourage project accountability by donating to trusted projects. Apply for verification and your donors will be rewarded with GIVbacks."

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/158233898-18dc4b3b-2afc-4bfc-96a0-1ececd035660.png)

"The GIVeconomy"
"Give, earn and govern using GIV and the GIVeconomy. Get rewarded for being a GIVer."

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/158234707-b46c9120-d7bc-4f05-bf10-857ecbdd5723.png)

"Subscribe to our newsletter to get monthly updates straight to your mailbox!"

**Comment by danelsuga** [comment]
Also, this hyphen needs to be removed. The kind of fees are « added fees ». It is not the case that there are fees which are of the « zero-added » kind. 

We demand how many added fees? Zero. 

Therefore the hyphen has got to go. 

(Sorry, hyphen! Incidentally, the name of my house is « Le trait d’union » which is « hyphen » in French! (Named thus because there are secret passages connecting the neighboring houses!) I know, crazy that my house has a name. It’s very old. Come visit! (Mateo and Griff (and Livia from TEC) have been here!! :D))

![image](https://user-images.githubusercontent.com/81351744/158371976-f49eeb64-4267-4025-aa18-2e0c0dd5ba87.jpeg)
