### ISSUE TITLE
Project filtering for Gnosis chain not working in all cases

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#1661]
**Describe the bug**
When I use the "Accept funds on Gnosis" it doesn't filter out all Giving Block projects

**To Reproduce**

When I add the "Accept funds on Gnosis" filter and search for something (like "water" for example) in the search bar I still get some projects that only allow donations on Mainnet like https://giveth.io/donate/napa-land-trust and https://giveth.io/donate/ymca-of-the-suncoast

**Expected behavior**
It shouldn't show any Giving Block projects (since they only allow donations on Mainnet)

**Screenshots**
<img width="1427" alt="Screen Shot 2022-10-17 at 6 06 33 PM" src="https://user-images.githubusercontent.com/4855928/196198630-6dd623b1-4ec1-4b4b-b53b-a5061ea707ec.png">

**Desktop (please complete the following information):**
 - Mac OS desktop
 - Browser Chrome

**Comment by maryjaf** [comment]
"Accept Funds on Gnosis" filter has been tested on stage
Now, the wallet address has not been set for this project"testfilter"
When the "Accept Funds on Gnosis" filter is disabled this project is displayed in result
![image](https://user-images.githubusercontent.com/111529185/196216923-e979cf00-f7bf-433d-99ae-67e24d7e08ee.png)
But after I activate the "Accept Funds on Gnosis" filter, this project is not displayed in search results
![image](https://user-images.githubusercontent.com/111529185/196217219-b0334464-bcb3-44a5-a2bd-4788cc49043e.png)

**Comment by MoeNick** [comment]
Hey @mohammadranjbarz and @maryjaf 
Ahmad is correct, this picture says it all, we have a problem I guess especially when it is supposed to be an AND between filter conditions and search conditions. 

![image](https://user-images.githubusercontent.com/80677512/196223184-5ba36c28-06f9-4bc6-b15d-3048b7f18013.png)

**Comment by mohammadranjbarz** [comment]
I fetched the info of one of giving blocks projects and I saw it has `gnosis(100)` address

<img width="929" alt="Screen Shot 1401-07-25 at 19 33 22" src="https://user-images.githubusercontent.com/9850545/196229120-4a29c517-82c7-482a-9fdf-de3e504acaaf.png">


So the problem is not he filtering, we made mistake in below migration when we wanted to fill addresses from project's walletAddress, we should have excluded giving blocks projects from adding gnosis addresses, now we have to write another migration to delete gnosis addresses of giving block projects and it would solve our problem

https://github.com/Giveth/impact-graph/blob/staging/migration/1654415838996-fillRelatedAddressesFromProjectsTable.ts#L78-L102


**JFYI** @MoeNick  @maryjaf

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz  for your explanation
I had tested the functionality  of this new filter on  my projects and everything was correct.
Unfortunately, I was not aware of this that Giving bloc k projects are only on Mainnet network, otherwise we would have noticed and fixed this problem before deployment.

**Comment by mohammadranjbarz** [comment]
@maryjaf  @ahmadabugosh  @MoeNick 

<img width="1431" alt="Screen Shot 1401-07-26 at 19 36 58" src="https://user-images.githubusercontent.com/9850545/196484537-9d15cb5f-5e3d-4f48-9e31-51de44322863.png">

It's working now
