### ISSUE TITLE
GIVpower boosting | Default project sorting should be by rank

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1736]
- [x] GIVpower rank should be the default way that projects are sorted... the project rank #1 should appear first, etc.
Unboosted, verified projects should be next
Nonverified projects should be third.

- [x] We should add a "sort by GIVpower rank"

- [x] We should add a filter "Boosted with GIVpower"

cc @MoeNick

**Comment by laurenluz** [comment]
who is the right person to take this? I can add more info, if needed. @aminlatifi @MohammadPCh @RamRamez

**Comment by MohammadPCh** [comment]
@laurenluz should we remove the "default" option?
![image](https://user-images.githubusercontent.com/17097576/199717948-0c94d27e-0831-48f2-954b-2628fb63b397.png)
if we make boosted as default sort option, it's meaning less to have another option called "Default". what do you think?

**Comment by laurenluz** [comment]
@MohammadPCh can we call it sort by "Rank" instead of by "Boosted"?

And sure - let's remove the default option and have just it say "Sort by Rank" as the default.

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  
Now we have **BoostedWithGivPower** filter to just get projects that their total power is more than zero

**Comment by MoeNick** [comment]
would u pls take a look and test?

**Comment by maryjaf** [comment]
Plz check this @mohammadranjbarz 
Rank of "elizabeth-glaser-pediatric-aids-foundation" is 3 in boosting
When I revoke the project, this project is still in the third position, with the difference that it has no rank
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/200846278-8f60efc3-99a7-44d0-9873-6e631f8ccd78.png">

**Comment by maryjaf** [comment]
> elizabeth-glaser-pediatric-aids-foundation

I should add that after a few minutes this problem will be solved and the project will not be displayed in position 3

**Comment by laurenluz** [comment]
@mohammadranjbarz 

A project can get unverified (or verified) at any time - it's not only at the start of the next round.
So, in this case, if a project is in rank 3, and then loses it's verified status, it should also lose it's rank and its position in the default sorting (it should go down to the bottom).

If it becomes re-verified mid-round and its GIVpower (and the GIVpower of all the projects) has not changed... it should once again appear in rank 3, position 3.

Does that make sense?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> A project can get unverified (or verified) at any time - it's not only at the start of the next round. So, in this case, if a project is in rank 3, and then loses it's verified status, it should also lose it's rank and its position in the default sorting (it should go down to the bottom).
> 
> If it becomes re-verified mid-round, it will start out at the very lowest rank (despite having GIVpower on it)... it's rank should update at the start of the next GIVbacks round, taking into consideration it's average GIVpower throughout the round.
> 
> Does that make sense?

@aminlatifi I think the best thing that we can do is removing all previous boosting snapshots of a project when it got unverified, so when refreshing `projectPowerView` it would not have any total power and rank,  do you think it meets what @laurenluz  mentioned?

**Comment by maryjaf** [comment]
This issue has not been resolved 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3e799a39-2d10-4269-b1c6-c6e3e98e81aa)

**Comment by aminlatifi** [comment]
> 

@laurenluz @mohammadranjbarz We save zero value for unverified projects in the snapshot-taking process. I think that would address the issue since if a project gets verified in mid-round, its positive givpower will be considered in next snapshots, consequently in the next round it won't have full power (in first snapshots of previous round it doesn't have any credit)

The issue  that project is on top for a few minutes after being unverified is because of two reasons:
1. In the get projects API, order by givpower amount precedes verified value.
```
      case SortingField.GIVPower:
        query
          .orderBy('projectPower.totalPower', OrderDirection.DESC, 'NULLS LAST')
          .addOrderBy(`project.verified`, OrderDirection.DESC);
```
That's the reason project will be still on top after it's unverified. We can reorder sorting fields and move the project to the end. But the project will still hold the rank position! 
2. We update (refresh) the project givpower view every 5 minutes and till then the project will hold the previous power amount and rank! To solve this we must add refreshing power-boosting-related views to the the unverify/verify  action processing sections.

**Comment by aminlatifi** [comment]
@mohammadranjbarz What do you think? if it's fine can you do it?

**Comment by aminlatifi** [comment]
@laurenluz Consider this scenario
A verified project has power gained by boosting in the previous round. If that project becomes unverified and again verified in the current round, we will show the same power value it had become unverified. But it will lose the power of snapshots that have been taken meanwhile it has been unverified, which will affect its power in the next round.
I hope it will be enough since the project was verified the whole previous round and now it's verified.

**Comment by aminlatifi** [comment]
> > A verified project has power gained by boosting in the previous round. If that project becomes unverified and again verified in the current round, we will show the same power value it had become unverified. But it will lose the power of snapshots that have been taken meanwhile it has been unverified, which will affect its power in the next round.
> 
> Shouldn't the power from the previous round not matter anymore in the current round? I thought our snapshots were considering only data from the current round to determine the rank for the next round. No?
> 
> I think I understand what you're saying though. Is this right? --> A project, if it's unverified at some point mid-round, and then re-verified at another point mid-round... will have:
> 
> * some power from the snapshots before it became unverified
> * zero power for snapshots mid-round
> * more power in the snapshots after being verified again...
> 
> and its totalpower affecting its new rank for the next round will be the average of all those, right? Because, if so, I think that's ok and we don't need to change that.
> 
> The only thing I want to make sure of is that if the project gets unverified it loses its position in the project list (which I think you guys are already solving).

Yes, you get it correctly 👍 
So it seems it's done.
