### ISSUE TITLE
"Connect your wallet" options in web3modal - Change modal to be wallet agnostic if the default is not metamask

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1818]
This came our of discussion with Tally Ho - an alternative browser wallet to metamask.

If the user has set their detault web3 wallet to a wallet other than metamask, it would be great to have the web3modal reflect that with a "connect to your web3 wallet option".

So, if the default web3 wallet is metamask, we can have the modal look like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/25ca1753-6c96-4e10-a537-e04d66c1dd2b)

And if their default wallet is any wallet besides metamask ,we can have the modal look like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/84f12698-b500-401b-b19a-dd442ed39cc2)

We are considering doing a comarketing campaign with Tally-Ho so it would be nice if our dApp was more web3 wallet agnostic.

Discussion in discord [here](https://discord.com/channels/679428761438912522/762764762164887562/1041739743777525900)

**Comment by laurenluz** [comment]
Here are their docs: https://docs.tally.cash/tally/developers/integrating-dapps

**Comment by laurenluz** [comment]
Sure thing!

So basically if the user's default web3 browser right now is NOT metamask (for example, if they were using tally ho wallet...), then they would get this popup and have to select "connect to metamask" in order to connect to their tally ho browser.

We should have the user experience compatible for people using web3 browser wallets that are not metamask... therefore... ideally, we can:
- check if their default browser wallet is metamask
- if yes --> show "connect to metamask" as the 1st option
- if not --> show "connect to web3 wallet" as the 1st option

Is it clear @RamRamez ?

**Comment by RamRamez** [comment]
I integrated TaHo web3 wallet with our dapp. You can test here:
https://giveth-dapps-v2-git-1818integratetahoweb3wallet-givethio.vercel.app/

TaHo wallet doesn't support customs chains (including Gnosis chain).
https://tahowallet.notion.site/Supported-Networks-1c00a0a3f83343cdba01b637f4147a5f

I can disable Gnosis chain in switch wallet modal and donate page for TaHo.
@laurenluz @MoeNick Do you want to do this?

**Comment by laurenluz** [comment]
oh no! damn, that makes things really strange if the user is trying to use Tally Ho...

I don't think it is a good idea to disable gnosis or other chains.

**Comment by MoeNick** [comment]
So shall we close it? @laurenluz ?

**Comment by RamRamez** [comment]
I talked with Nax and told me they are working on adding custom chains, but there's no estimation of when it will be ready.

**Comment by divine-comedian** [comment]
I want to bring this one back up! We should change the MetaMask icon to become something more generic 

Since clicking this option will grab whatever it can in window.ethereum (right??) it may load a wallet that is not metamask by default.

For example in this video I have the metamask browser extension disabled and instead phantom Wallet pops up since I have it installed an enabled in my browser

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ecce542e-6cd9-47c0-b1be-e21e4104cf3a

## To be clear we should:

Change this MetaMask panel to say "Wallet Extension | MetaMask" & subtext should read "Connect with your installed web wallet." : 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c864c1d2-c479-40ed-a9da-74bde87b4ce5)

& we can also use this image from the design system and place it adjacent to the MM logo (centered)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8eb9d3fa-fee9-4ad1-8933-bdd55101f934)


Does this make sense? @alireza-sharifpour can you check it out?

**Comment by alireza-sharifpour** [comment]
Hey, I think a lot of users look out for the MetaMask icon when connecting their wallets, right? Since so many use MetaMask, changing the icon too much might confuse them. What do you guys think, @divine-comedian and @mosaeedi? Meanwhile, I've changed it to this:

<img width="448" alt="Screenshot 2023-08-20 at 11 40 35 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/f15b63a9-73a4-4634-85d1-d5d4db9ad43e">

**Comment by divine-comedian** [comment]
Until we add the wallet connect integration I think this is the best we can offer!

**Comment by maryjaf** [comment]
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWtlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--60f408fc1f64b065bc47f79328afb3d15e27ea3c/image.png)
Thanks @alireza-sharifpour
