### ISSUE TITLE
GIVpower Boosting | Handling GIVpoewr for canceled projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1837]
@mohammadranjbarz Can you have a look?

Check to see what is happening with GIVpoewr when a project is cancelled. We are thinking it would be good - if a project becomes cancelled - then we make GIVpower on it all set to zero... so each user's GIVpower gets proportionally added to their other project.

let me know if you have any questions.

**Comment by laurenluz** [comment]
cc @aminlatifi

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick 
It's on staging, you can test it now

**Comment by laurenluz** [comment]
@maryjaf please test :)

**Comment by maryjaf** [comment]
When the canceled project becomes active again,what is the expectation?
Now it is the case that the project's rank returns to the previous rank, but the project hasn't any boost
I think the projected and current rank changed to "--" because it hasn't any boost
[Uploading... image.png]

**Comment by mohammadranjbarz** [comment]
@maryjaf 

Now when we cancel a project we remove all boostings of that project and change the other project's percentages for users who boosted the project, but we don't change the snapshot data , so when we activate it again the ranking would appear because in current round it had some snapshots, but for next rounds it would not have any rank, I talked 2ith @aminlatifi  and he thinks it's ok but @laurenluz  you tell me what should we do.
I think it's really a rare case that we cancel a project and activate it in the same round so we can skip this.
please tell me the decision I would it

**Comment by laurenluz** [comment]
Hey @mohammadranjbarz ! I think that is ok. It's a super rare case, as you said. I like removing all the boostings and changing the other project's percentages, and think it is ok that we don't change the snapshot data.

Once this is built, let's move it to get tested :)

**Comment by maryjaf** [comment]
I tested this, and after canceling the project, the boosts of this project are properly eliminated and assigned to other user's projects.
The only problem with the reactivation I raised above is and is accepted according to the conversation
