### ISSUE TITLE
GIVpower Boosting | Change copy on "oops modal" when a user is trying to remove their last project boost

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1871]
**Describe the bug**
My user have one boosted project that this project has been unverified
When I try to remove this from  list  I got an error
![image](https://user-images.githubusercontent.com/111529185/204050154-d360079f-4320-4353-b3ec-f9f755bf8b0f.png)
![image](https://user-images.githubusercontent.com/111529185/204050169-7a7df67a-96d9-49f4-9e3b-088243afe26c.png)

**Comment by MoeNick** [comment]
@laurenluz what should we do in this case?

**Comment by laurenluz** [comment]
Maybe we can just change the copy on the modal to give some better recommendations for next steps. So:

Oops!
You can't remove your GIVpower from this project because it is the only boost you have.
Please boost another project with GIVpower before continuing.
Button: Go to Project Page
Small text: Dismiss

@MohammadPCh @divine-comedian think this is ok? It's an edge case, and I think better copy helps.. also the better copy will help in general because people find the "you always just be boosting" thing confusing ( see https://github.com/Giveth/GIVeconomy/issues/825)

**Comment by divine-comedian** [comment]
I think it's an edge case and better copy would be "good enough" hopefully unverified projects aren't a common occurrence so we shouldn't break our heads finding a complicated solution.

**Comment by divine-comedian** [comment]
resolved in https://github.com/Giveth/giveth-dapps-v2/commit/f31ec235791b11c21c712d8f26dc4b867ef86645

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks man :)

**Comment by maryjaf** [comment]
Thanks @divine-comedian 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/111529185/204760536-9b873bbb-ab9e-47cc-bdc9-26323cf0593d.png">
