### ISSUE TITLE
Allow users to open project pages in a new tab

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1907]
**As a user looking to open several projects at once, I want to be able to open projects' description page in a new tab, so if i'm scrolling thru the projects on the home page I don't have to start all over from the beginning again.**

We can open the donate page in a new tab, but we can't right click the project and open it in a new tab.

**Comment by mosaeedi** [comment]
IMHO, both option has their pros and cons!
Opening a new tab means for a user who is opening many projects at once, the user flow won't be interrupted,
but for another user, it might be a little confusing because they may not notice that the project is actually opened in a new tab and they end up opening a project more than once!

I think it's better if we think about this a bit more and then do something.

**Comment by laurenluz** [comment]
At the very least, it should be possible to right click and open a project in a new tab.

Right now, it's really annoying that you can browse projects, open a bunch of tabs, and then go through them. It feels very limiting.

@mosaeedi @MoeNick

**Comment by laurenluz** [comment]
oh strange, I just tested again, and that works fine for me as well. I remember before I couldn't do that.

tbh, I'm pretty neutral on opening projects in a new tab by default then. I kind of like the seamless feel of just using one tab, unless you specifically intend to open more.

@GriffGreen - are you having an issue w/ this?

**Comment by MoeNick** [comment]
@brichis maybe you can ask @GriffGreen, I think we can close this.

**Comment by brichis** [comment]
Hey @MoeNick, sure let me tell him :)

**Comment by GriffGreen** [comment]
Works great!
