### ISSUE TITLE
Search function Bug - can't find a verified project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1936]
Can't find "Regens unite" when I search for it. I get this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f44a875d-991b-4923-a643-53959eba37e8)

https://giveth.io/project/regens-unite

I think there is a bug w/ our search.

@MoeNick - who is the right person for this? @RamRamez ? @alireza-sharifpour ?

**Comment by alireza-sharifpour** [comment]
I tested it and int works fine for me!
Have you added any other filters besides the search string?
@laurenluz 

![Screen Shot 2022-12-14 at 11 19 16 AM](https://user-images.githubusercontent.com/48887817/207536745-7b96e91a-ec1f-485a-ae9d-c0f570dec59e.png)

**Comment by laurenluz** [comment]
no, I didn't have other filters, and actually, this issue came from another user on twitter: https://twitter.com/krrisis/status/1602731641533009920

**Comment by alireza-sharifpour** [comment]
Because I don't have this issue when i'm testing I need some information from when the problem occurs.
Could you please open the google chrome developer tools and send me the payload of the request that goes to backend?
This is the exact thing we are sending to the backend and getting the result.
![Screen Shot 2022-12-15 at 9 14 59 AM](https://user-images.githubusercontent.com/48887817/207782155-3a0fcc28-5267-4285-b373-118c013505b6.png)
@laurenluz

**Comment by laurenluz** [comment]
weird :( it's working for me now too. But it wasn't when I posted the issue

**Comment by laurenluz** [comment]
I think we can close this for now, if they get back to me with a problem I'll get them to send me the payload of the request.
