### ISSUE TITLE
Incorrect display of number of pagination in Givpower tab

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1974]
**Describe the bug**
Incorrect display of number of pagination in Givpower tab
**To Reproduce**
1. Go to 'https://giveth.io/project/the-giveth-community-of-makers?open=boost'
2. Click on 'GivPower'
3. Scroll down to end of table
4. See "5" pages although "2" pages have data

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/111529185/209694867-0aa24930-a56d-4e97-9580-23c92431c03b.png">

**Comment by MohammadPCh** [comment]
Thanks @maryjaf,
@mohammadranjbarz could you please take a look?
![image](https://user-images.githubusercontent.com/17097576/209769928-a97a0528-d8ab-48ca-b34b-bb8990df6954.png)
the totalCount is wrong.

**Comment by mohammadranjbarz** [comment]
@MohammadPCh We have `41` power boostings for this project, in this web service we get two parameters `take` and `skip`, the default value for `take` is `20` and the default value for `skip` is zero, so when you call it you would get the first `20` items, if you want to get rest of items you would call another request, but if you want to get all power boosting in one request , you can tell me to change the default value and return more items instead of `20`

**Comment by MohammadPCh** [comment]
@mohammadranjbarz 
I don't pass the take because we talked about it and we decided to handle the pagination in the front end.
I think it's better to get all of them at once. because it's confusing to have two paginations :smile:

**Comment by aminlatifi** [comment]
> @mohammadranjbarz I don't pass the take because we talked about it and we decided to handle the pagination in the front end. I think it's better to get all of them at once. because it's confusing to have two paginations 😄

If we rely on the front end for pagination, there will be an issue if the number of boosters becomes huge. First, this huge data will be fetched every time users visit the first page which is not efficient. Moreover, it could be impossible to fetch huge data in one query

**Comment by mohammadranjbarz** [comment]
> If we rely on the front end for pagination, there will be an issue if the number of boosters becomes huge. First, this huge data will be fetched every time users visit the first page which is not efficient. Moreover, it could be impossible to fetch huge data in one query

@aminlatifi  Frontend needs all the data in one request, because for showing all boosted givPowers, needs to get givPower balance of all users, do you have any idea for solving that?
<img width="1068" alt="Screen Shot 1401-10-08 at 16 20 08" src="https://user-images.githubusercontent.com/9850545/209953496-1d9555ab-64cb-460f-a266-fed4f68344c6.png">

**Comment by aminlatifi** [comment]
@mohammadranjbarz I forgot it!! BTW, I think we still need to keep pagination but with bigger chunk size!

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's on production and staging ( now we support too many givPowers in that list)

**Comment by maryjaf** [comment]
> @maryjaf It's on production and staging ( now we support too many givPowers in that list)

Thanks @mohammadranjbarz I checked it on production and it has been fixed
