### ISSUE TITLE
Add Gitcoin Grants banner to giveth.io ASAP

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2050]
@rodricastillo9013 preparred this banner:

![image](https://user-images.githubusercontent.com/75490971/213466702-a6848269-3334-4a09-ae42-460e0d6d1272.png)

It should link (for now) just to our grant here:

https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c/0xb746c0f648f9b930ea4568cf8741067a7fc7eb3928ac13cced8076212cf3cf37-0xd95a1969c41112cee9a2c931e849bcef36a16f4c

FYI - @mosaeedi is working on making a landing page so you can click the banner, get to a landing page and from there go to one of two links - our grant and the refi DAO grant, but design won't be ready until friday and I want this up asap with an MVP.

It would be great to see this in two places:
- at the top of the projects page before the projects
- on the homepage, replacing "feeling $nice" (for now).. we can put the $nice banner back later after the grants round ends

**Comment by laurenluz** [comment]
Ok! @mosaeedi made a fantastic revised design for this. We should replace the current production version w/ this [figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263143&t=Kv4xAhLsJTdBwNV5-4)

Basially, clicking on the banner in either spot (from homepage or projects page) and you get to this landing page.

The landing page must be built that I think should have a unique URL like: giveth.io/gitcoingrants

All the copy in the figma on the landing page is up to date.

There are two links in the figma going to two different grants... I linked them as comments in the figma.

@mosaeedi also prepped the repsonsive versions.

Who can do this asap? @mateodaza @RamRamez @MohammadPCh @alireza-sharifpour

**Comment by MohammadPCh** [comment]
@mateodaza Good luck bro, let me know if you need any help on this.

**Comment by mosaeedi** [comment]
# Design resources


**Background gradient**
background: linear-gradient(263.96deg, #211985 43.14%, #5326EC 75.18%);

Elements on the banner
Download here -> [Gitcoin banner.zip](https://github.com/Giveth/giveth-dapps-v2/files/10471805/Gitcoin.banner.zip)


## Note

The **Giveth hand.svg** & the **Refi x Commons circles.svg** should not be fixed so that they can move and rearrange on different display sizes.

---

## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263484&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263484&t=88DCvbOSZF2tOiMF-4)

**(>1024 - <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263582&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263582&t=88DCvbOSZF2tOiMF-4)

**(>768 - 1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263680&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263680&t=88DCvbOSZF2tOiMF-4)

**( Mobile )**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263778&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18639%3A263778&t=88DCvbOSZF2tOiMF-4)

---

## Flow

1. the banner should be on top of the project list on the projects screen
2. When the user tap on the **Donate now** they will go to the **Donate to Giveth** screen where they can see both options to donate to
!Note: On the second screen the banner doesn't have any **Donate** button.


### Project screen
<img width="882" alt="Screenshot 2023-01-21 at 12 26 18 PM" src="https://user-images.githubusercontent.com/13708322/213859822-8e95d25d-bec8-4b5d-9dd1-7918a8869f35.png">

### Donate to Giveth screen
<img width="749" alt="Screenshot 2023-01-21 at 12 27 34 PM" src="https://user-images.githubusercontent.com/13708322/213859863-c102582c-6f9d-4434-b671-592e83b5221b.png">

**Comment by MoeNick** [comment]
@mateodaza pleeeeeeeeeeeeease related the PR! :) and please tag @maryjaf for QAing even if it is pushed to production to get a better idea about the required spec. 

and @mosaeedi if you can tale a look at design confirmation it would be appreciated.

**Comment by mateodaza** [comment]
@MoeNick yes sir!

**Comment by MoeNick** [comment]
@maryjaf please take alook at this.

**Comment by laurenluz** [comment]
@mateodaza - the banner on the homepage & projects page is still the old version - can you update it please?

**Comment by mosaeedi** [comment]
@mateodaza Can you please remove the white background and also fix the top padding!? the top padding should be 40px
Also, the banner and the content max width is 1200 px, but on the live version, the banner is a little smaller than the content area.

**"We’d love your support in Gitcoin Grants"** this line should be H4/700, but it's 500 weight now.

**Comment by laurenluz** [comment]
Actually, we should hide this banner now/comment it out.

Gitcoin alpha round is over

I think we can keep the landing page via the URL... but we just don't have a banner linking to it anymore @mateodaza

**Comment by mateodaza** [comment]
> Actually, we should hide this banner now/comment it out.
> 
> 
> 
> Gitcoin alpha round is over
> 
> 
> 
> I think we can keep the landing page via the URL... but we just don't have a banner linking to it anymore @mateodaza 

Ok understood!

**Comment by laurenluz** [comment]
Thank you!! <3
