### ISSUE TITLE
Homepage | "What's up on Giveth" Content for launch

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2242]
I would love to see 3 featured pieces in "what's up" at launch.

1. Impact Quests

Title --> Impact Quests at ETH Denver
Subtext --> Complete virtual quests designed to make a positive impact on Denver, and win awesome prizes!
Media --> (if we can get a better banner from Rodri, great... if not...) ![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9ffd767d-46c3-4c5f-a399-213c247b74ba)
Link --> Text "Explore Quests" --> https://giveth.io/quests

2. GIVpower

Title --> GIVpower is here!
Subtext --> Boost verified projects and help them get a higher rank on Giveth.
Media --> should be the GIVpower video
Link --> Text "Learn more" --> https://giveth.io/givpower

3. $nice

Title --> Feeling $nice?
Subtext --> Donate eligible tokens to Giveth and receive $nice, redeemable for swag and much more!
Media --> ![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2fa71277-9cea-4830-8392-c170f3fe98e7)
Link --> Text "Donate now" --> https://giveth.io/project/the-giveth-community-of-makers

cc @MoeNick @c0ric0ri

**Comment by MoeNick** [comment]
![image](https://user-images.githubusercontent.com/80677512/221413116-01bda168-a4c7-4d67-90c5-ab93efc48aff.png)

I made these campaigns on Admin:

- IsActive: means we show it at all or not! kinda hide
- Is New: means we show it in what up block or not. 
- Is Featured: it means it has relevant projects to show on the featured block or not. 
- Order means the order of slides in what's up block

For now, the featured block on the homepage is set for EthDenver, as @c0ric0ri said we want them for a week, however, it's possible to have two blocks for FeaturedProjects, one for turkey and one for Eth Denver

I added Turkey to what's up for now because I removed the featured projects temporarily! 

Please take a look on production and lemme know what do you think.

**Comment by MoeNick** [comment]
jfyi, we are obliged to change the pictures to follow the required dimensions.

**Comment by laurenluz** [comment]
oh, I just made an issue #2265 because I noticed some things were off here. 

Regarding the image.. we can't just crop a meme and call it good. it's missing the bottom text and looks bad. either we need a replacement image (something that explains impact quests) or we need to find a solution so that the meme is not cropped.

**Comment by MoeNick** [comment]
> oh, I just made an issue #2265 because I noticed some things were off here.
> 
> Regarding the image.. we can't just crop a meme and call it good. it's missing the bottom text and looks bad. either we need a replacement image (something that explains impact quests) or we need to find a solution so that the meme is not cropped.

As @mosaeedi send us this graphic, I think he has to be involved, wdyt @mosaeedi ?

**Comment by MoeNick** [comment]
As we talked with @laurenluz we decided to use this picture for Quest, and I uploaded it.
![image](https://user-images.githubusercontent.com/80677512/221430458-c0e5770a-9c42-446e-9f11-ad6c7a0b7499.png)
