### ISSUE TITLE
There are no tokens in the token list ??

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#245]
I'm connected to ropsten and testing on the [testing site](https://giveth-dapps-v2.vercel.app/donate/ymca-of-the-suncoast)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c22f2ecf-f0c9-4862-b05f-b334aceb055f)

**Comment by laurenluz** [comment]
This is a giving block project btw

**Comment by mateodaza** [comment]
Are you on mainnet?

**Comment by GriffGreen** [comment]
Ok so we need to tell them to switch to mainnet

**Comment by mateodaza** [comment]
> Ok so we need to tell them to switch to mainnet

yes, working on a new modal now for that :)
Thanks for noticing, @MoeNick also told me that but we totally missed it for launch

**Comment by GriffGreen** [comment]
Same issue
<img width="1105" alt="Screen Shot 2022-03-16 at 2 29 05 PM" src="https://user-images.githubusercontent.com/14945613/158674774-53c8e179-9e01-4ce0-b5bd-b44c46c704cc.png">

then when i switch to mainnet i get this: 
<img width="1256" alt="Screen Shot 2022-03-16 at 2 31 09 PM" src="https://user-images.githubusercontent.com/14945613/158674900-20395cd6-accd-4aa0-976f-06c44e9f7fd2.png">

**Comment by GriffGreen** [comment]
Then when i close the modal i still see no tokens... even after refresh
<img width="1385" alt="Screen Shot 2022-03-16 at 2 32 03 PM" src="https://user-images.githubusercontent.com/14945613/158675056-bd816a69-b3c2-4905-81d4-5052456788ba.png">

**Comment by mateodaza** [comment]
On it!

**Comment by MoeNick** [comment]
I'm still having problems with donations to these giving block projects
the token list on both chains are empty. 
the modal also appears when I'm on the right network. 
@mateodaza @pkretzschmar

**Comment by mateodaza** [comment]
This is not on staging yet

**Comment by mohammadranjbarz** [comment]
@mateodaza  You can get valid tokens for project from backend
https://github.com/Giveth/impact-graph/issues/380#issuecomment-1068337179

**Comment by divine-comedian** [comment]
tokens show up on ropsten now 

![image](https://user-images.githubusercontent.com/67759413/161101659-0f97a2f7-ae9e-48b3-9227-c8c3d8b4dd93.png)

however it is still empty for when im on ropsten on giving block - probably because they don't accept donations on ropsten

on mainnet I get the popup to switch to mainnet - however im on staging so it probably means ropsten - no tokens show up in the token list while connected to mainnet on a giving block project on `staging.giveth.io` 

is this broken or something funny because of using ropsten on staging with giving block projects? 
@RamRamez

**Comment by CarlosQ96** [comment]
Working on this for staging, adding the ropsten list for givingblocks tokens.

**Comment by mateodaza** [comment]
Solved this on last PR as well (not merged), so they can be seen in staging as well
