### ISSUE TITLE
Set up passport scorer for production environment

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2461]

**Comment by laurenluz** [comment]
this should be done via multisig, here: https://scorer.gitcoin.co/#/new-scorer

The scorer is what determines a user's passport score.

**Comment by laurenluz** [comment]
As discussed in discord, we need to set up a new gitcoin passport scorer for our production environment.

Carlos will generate a new private key for this (and will share with Kay) and will set up the new scorer.

Then, we should integrate this into staging to test.

Sound about right @CarlosQ96 ?

cc @MoeNick @maryjaf

**Comment by maryjaf** [comment]
> CorrecT! Ill do it today.

@CarlosQ96 plz let me know when it's ready to test
I think I don't know much about this change and plz explain to me about that

**Comment by CarlosQ96** [comment]
@maryjaf basically we are changing the wallet address that we were using to generate the gitcoin api key. Because the gitcoin scorer was using my personal account.

I switched it another wallet and sent the private key to @geleeroyale 

Nothing of functionality changed, everything should work as its working now regarding refreshing the score.

Might take a bit to load the score when refreshing but that is normal behaviour.

**Comment by CarlosQ96** [comment]
Moved to QA.

**Comment by laurenluz** [comment]
so @maryjaf - if you can just do some basic testing to make sure that everything related to passport is working as before... that will be it.
