### ISSUE TITLE
Idea generation for "perks" or use cases of getting passport score in Giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2464]

**Comment by laurenluz** [comment]
from giveconomy call:

when people donate to projects they will get reputation token, so we can use quadratic voting etc.
if we get grant from EF, we will want donor uniqueness

**Comment by divine-comedian** [comment]
Is there any reason we can't just copy the benefits from the original Gitcoin mechanism? That was where the more you verify the more matching you generate - for me that was a pretty strong incentive! 

I hear from others and agree that we should absolutely not add any more complexity to how we calculate GIVbacks.

**Comment by laurenluz** [comment]
yeah well the idea is that we could use passport beyond just QF rounds eventually, but I think for now it's ok to just confine it to "donors in gitcoin rounds"

Noted on GIVbacks, let's get rid of that idea.

And I think that's a cool idea with like higher score = more matching... I'm not sure it's possible, it is not the way Gitcoin uses passport in theiw QF rounds currently. I'll look into it.

**Comment by WhyldWanderer** [comment]
I would like to also say that we shouldn't make GIVbacks more complicated...

Maybe we can easily do some cool esthetic things... like a checkmark or something cool around their profile picture to signify that they have verified a certain number of stamps in their passport... we could also spruce up their user profile page somehow with a cool design, 

Maybe they could get a higher percentage of $nice tokens when they donate to Giveth? Maybe instead of 1:1 its 1:1.25 or something? idk

Maybe there is some incentive for donating to the matching pool if you are a unique donor?

Will the stamps also refresh and need to be reverified periodically? 

Random thoughts....
