### ISSUE TITLE
Disable Submit Update Button after submitting. 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2468]
Browser: Brave Browser
Ubuntu 22.04
giveth.io - production

Currently on production I receive duplicate notifications fairly frequently 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/73b04665-bc53-486c-91fd-c0975adb2cf3)

I checked on the relevant projects and only 1 update was posted but I get two notifications. 

### Expected Behaviour:
I should only receive 1 notification per relevant project update

**Comment by MoeNick** [comment]
@maryjaf to find the route cause would you please play with { donate, boost or like} ing a project to see which combination of those makes these notifs duplicated?

**Comment by maryjaf** [comment]
> @maryjaf to find the route cause would you please play with { donate, boost or like} ing a project to see which combination of those makes these notifs duplicated?

I checked different scenarios and checked the projects whose update notifications were sent more than once at the same time.
I think that by entering the update and selecting the submit option more than once , this happens and causes several identical updates to be registered.
And after that, the user deletes duplicate updates, and that's why we see one update but two notifications.

To avoid this, it is better to disable the ability to select submit more than once

**Comment by MoeNick** [comment]
@maryjaf pls take a look again.

**Comment by maryjaf** [comment]
when I selected one of my projects, I received an error as below pic ,plz check @RamRamez 
https://giveth-dapps-v2-git-2468disablesubmitupdatebutt-303b3f-givethio.vercel.app/project/testcelo
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7264fc70-c8a8-4e04-8fba-294a618823e9)

**Comment by RamRamez** [comment]
@maryjaf My PR is merged on staging, please test it on staging.

[https://staging.giveth.io/project/testcelo](https://staging.giveth.io/project/testcelo)
