### ISSUE TITLE
Referral program - We MUST make the UX better. Let's start by modifying "your link"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2513]
Ok... so this has been bugging me since I tested the program, and now it feels even bigger.

Right now, the process for referring people is super high friction. My referral link directs them to chainvine... then they have to read a bunch of craziness about the referral program... connect their wallet, sign and then click a tiny "Start" button to finally get to Giveth where they can donate.

This is total insanity, and no new donor is going to do it.

Can we:

1. Modify the "your referral link" out of being a link to chainvine, and actually just a link to giveth w/ my referrer id? like this: https://giveth.io/projects?referrer_id=3GuXx2t7U5SkJ5o5QhGwvJfHTav2 ?

Will that work?

2. Also... can we somehow make an easy flow or explainer so that people can generate referal links to specific projects using their cookie id... so that a referrer could recommend a particular project?

like this? 

https://giveth.io/donate/the-living-library-sanctuary-for-sacred-plants?referrer_id=3GuXx2t7U5SkJ5o5QhGwvJfHTav2

Will THAT work?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/300046cb-1dad-407a-ad8d-fd1b0a4f4f45)

@CarlosQ96 @ahmadabugosh @MoeNick

**Comment by MoeNick** [comment]
Then we have to implement it ourselves and its possible but without chain-vine. Im referring you to the discussions in the forum which @MohammadPCh suggested.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @MoeNick ,

We were actually just talking to Chainvine about this yesterday! They have an option to make the Chainvine landing page just for referrers but the people completing the action would get the link directly, like you suggested. We're testing that out now and I'll keep you posted! That would take out the step of new donors needing to go to Chainvine at all. 

For the second point about unique links for projects, that is possible and we actually had that feature activated before, but testers found it very confusing (since it was just a text field where you could paste any url for any project but it added more friction and wasn't very clear) so we removed it. We can add it again, but we need to figure out a way to make it simple from a UX perspective, otherwise it would do more harm than good.  It shouldn't be too hard to make a short guide explaining how projects can generate it themselves though.

**Comment by laurenluz** [comment]
Hey @ahmadabugosh  any update on making the landing page for referrers?

I think we should add this option and then make it more clear to users... pasting in the URL and generating the referral link for that project shouldn't be too hard to explain... especially if the landing page has just ONE audience (referrers).

**Comment by ahmadabugosh** [comment]
@laurenluz We have a call with them this week. I'll bring up how we can quickly move to this and also re-add the option to let them generate a project referral link as well.

**Comment by divine-comedian** [comment]
Is this issue still relevant? @ahmadabugosh

**Comment by ahmadabugosh** [comment]
@divine-comedian We can close it, since we moved to our own referrals on-site
