### ISSUE TITLE
Changing the copy of I'm a giver draft tweet, adding more chains

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2529]
Here after the donation, copy of tweet should change:

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/b304822f-01f8-48cd-b581-ea65046ddcec)

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/35580f08-0897-455c-a61f-1c0b58816b5b)

Also, linked-in sharing is a buggy/.

**Comment by laurenluz** [comment]
How about:

I just donated to this awesome project on @Giveth! 💜  Read about their impact or support them here: <project link>

@MoeNick are there more tweets on the dapp? we should change them all since @givethio is not our handle anymore.

**Comment by RamRamez** [comment]
> How about:
> 
> I just donated to this awesome project on @Giveth! 💜 Read about their impact or support them here: < project link >
> 
> @MoeNick are there more tweets on the dapp? we should change them all since @givethio is not our handle anymore.

Twitter and YouTube handles are updated on staging. (#2542)

**Comment by laurenluz** [comment]
Let's change the others too - the copy is all weird now since we have more chains & changed our handle!

1- Footer of donation page with this copy:
This project is raising funds in crypto on @Giveth! 💜 
100% of every donation goes directly to the project to help them make an impact. Check it out 👇 < project link >

2- High-five page, (successful project creation)
Our project is raising funds in crypto on @Giveth! 💜 
100% of every donation goes directly to our wallet to help us make an impact. Check out our project here 👇 < project link >

and we have another component share in :
3- Projects card (in the project's page and in single project view donate card.
This project is raising funds in crypto on @Giveth! 💜 
100% of every donation goes directly to the project to help them make an impact. Check it out 👇 < project link >

@RamRamez - can you change these too?
