### ISSUE TITLE
When viewing my own verified project, it gives me the option to verify

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#254]
This is confusing for the user... to see "verify your project" when my project is already verified. This button should show up I think only for non-verified projects.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/97be8a7d-3caf-4c1a-a990-9472f0567cd4)

**Comment by divine-comedian** [comment]
I'm viewing one of my verified projects on `staging.giveth.io` 

instead of the verify project button I see `PUBLISH PROJECT`

I think this is supposed to be a toggle for activating or deactivating my project. the text is a bit confusing.

When I click PUBLISH PROJECT it instead asks me if I want to deactivate my project. 

We already have a place for deactivating projects on the UI, what is the intent of this second button? Is it possible to simply remove the button altogether if the project is already verified?

![image](https://user-images.githubusercontent.com/67759413/159364378-609f6adf-b36c-4452-914b-f03fb6df31e2.png)

@pkretzschmar

**Comment by divine-comedian** [comment]
Viewing my verified and listed project on `staging.giveth.io` 

I can still see this publish button. Pressing it takes me to the high five page which doesn't make sense since my project was already live. I can return to my project page and press this `publish project` button infinitely 

this feels pretty broken - ideally if my project is live and not in `draft` I shouldn't see a button here at all.

![image](https://user-images.githubusercontent.com/67759413/160039465-1230300b-6fec-4809-96bf-05e0489d7bb6.png)
