### ISSUE TITLE
Public view | Story sub tab

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2555]
Please note:

Take a look at the structure below.

![Screenshot 2023-04-24 at 2.01.48 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/bec86f4b-d417-4e5e-a8f7-a091990c59cc)

## Responsive resource

WIP

## Check the design

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=900-57923&t=yMkADlANl4In8UtA-4)

**Comment by mosaeedi** [comment]
Since we don't have the backend ready for showing other tabs, we show all of the **About project details** under the story for now! 

**Please note:** 
1. The project story should take 100% of the content area.
2. The **Our story** title is hidden for now.


Please take a look at the screenshot below. 

![Screenshot 2023-05-01 at 3.50.50 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a3a22628-33a7-43d5-87ac-9663de8de15f)
