### ISSUE TITLE
Use SVG token for token icons in donate menu

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#2593]
MoeSaeedi has a list of svg icons of all almost all tokens we have for donation. Let's use them for tokens.

Let's save them first in the design system

**Comment by RamRamez** [comment]
We have 549 token icons on Figma. The file names of some tokens are not exactly the same as their symbol, so someone should check all filenames one by one. (That's because `TokenPicker` component chooses the icon file from the token symbol)

Besides that, there's a special format in the design system for icon components. We can't just copy and paste them. Someone should create those components in the design system for all tokens one by one.

It's really time-consuming.

@MohammadPCh what do you think?

**Comment by MohammadPCh** [comment]
Ok I talked to @mosaeedi, and we started converting them. he is working to complete our icons because we don't have all of the token's icons.

**Comment by MohammadPCh** [comment]
JFYI, I got the list of tokens that we have in production from DB, and try to find them in the list of our tokens in Figma.
this is the result:
We support 179 tokens in different chains. we don't have an icon for 65 tokens. @mosaeedi is working on it to find them.
