### ISSUE TITLE
Backend for managing start time of referrals

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2616]
We need to manage the timestamp for when someone clicks the referral link in our database. We need to implement their API

@CarlosQ96 you know better than me what needs to happen here!

**Comment by MoeNick** [comment]
Hey @CarlosQ96 can we move this issue forward, if it's still needs work, can you updates us when we can deliver it?
FYI @ahmadabugosh @laurenluz

**Comment by MoeNick** [comment]
Can you attach the PR?

**Comment by CarlosQ96** [comment]
Here is the Pr: https://github.com/Giveth/impact-graph/pull/991 @mohammadranjbarz  @aminlatifi if one of you could double check, we moved forwards with the frontend integration @MoeNick .  
Tests work and Ci says everything it's fine.

However,  when I deploy to staging or develop the server breaks. It seems my migration won't run, I got stuck with this issue, seems I lack some env vars on my local to reproduce it or my db is out of sync (since we recently remove db sync).

**Comment by mohammadranjbarz** [comment]
> Here is the Pr: [Giveth/impact-graph#991](https://github.com/Giveth/impact-graph/pull/991) @mohammadranjbarz  @aminlatifi if one of you could double check the migration, we moved forwards with the frontend integration a bit @MoeNick . Tests work and Ci says everything it's fine.
> 
> However, when I deploy to staging or develop the server breaks. It seems my migration won't run, I got stuck with this issue, seems I lack some env vars on my local to reproduce it or my db is out of sync (since we recently remove db sync).

@CarlosQ96  I fixed and approved that PR
https://github.com/Giveth/impact-graph/pull/991#issuecomment-1549362944

**Comment by CarlosQ96** [comment]
Thanks Mohammad

**Comment by maryjaf** [comment]
How can I test this ? @CarlosQ96
