### ISSUE TITLE
When we harvest from the GّIVstream page, it is not recorded in the  history table

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2648]
**Describe the bug**
When we harvest from the GّIVstream page, it is not recorded in the  history table but when harvest from GIVfarm it is recorded in History table as below pic
**To Reproduce**
1. Go to 'GIVstream'
2. Click on 'Harvest'
3. complete the harvest process 
4. No record is recorded in the table

**Expected behavior**
Like when we harvest from Givfarm, a new record should be registered in the table after the harvest from the GIVstream page
**Screenshots**
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4e9a6730-d28f-4e44-b182-f4b273fb6839">

**Comment by MohammadPCh** [comment]
Thanks, @maryjaf 
It's Our expected behavior.
when we harvest from GIVfarm, It contains farm's rewards so, we have to show it in the history table, but when we harvest from the GIVstream page, we only harvest the streamed rewards, and it doesn't contain new rewards. so we don't need to show it here.
