### ISSUE TITLE
Bug on the projects page projects ranking + missing project

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#2813]
**Describe the bug**
I see the projects in an order different to the one marked by GIVpower & I can't find the Giveth matching pool project on the projects page.

**To Reproduce**
1. Go to https://giveth.io/projects

**Expected behavior**
Right order. All projects visible.

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/101358184/94e01d42-dcd3-4532-b15b-0fed9499982d)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - Browser [e.g. chrome, safari] Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by divine-comedian** [comment]
That's true! I took a screen capture of the ordering it's very confusing to see the filter to order by GIVpower then not have them in order based on their little rank tag on the project card. 

I think this issue was created from the instant boost feature that was implemented. 

Maybe @laurenluz has thought of something? Maybe we remove the ranking tag altogether on the project card?

**Comment by laurenluz** [comment]
yeah, I want to remove the rank. the rank is basically meaningless at this point because we added the GIVbacks % to the project single page & implemented instant boosting.

As a quick fix for now, I'd be ok with removing the rank from the project card.
