### ISSUE TITLE
New design: "verify your project" button

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2823]
**Describe the bug**
The status of verification is verified and the button of verify your project is shown @MoeNick @MohammadPCh 
**To Reproduce**
1. Go to 'my project'
2. Click on 'a project with verified status'
3. See the problem

**Screenshots**
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/86ecd6a7-1130-427c-b9bd-3a6ba2f7da92">

**Comment by MohammadPCh** [comment]
@MoeNick @mosaeedi Do we have a design for it? (please attach figma link i can't find it :cry: )
also, we want the copy for tooltips.

**Comment by maryjaf** [comment]
<img width="1430" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4c7a438a-e4dc-4361-be68-2d9c83e59633">

**Comment by laurenluz** [comment]
I think we have modified the design for the owner view here... https://github.com/Giveth/giveth-dapps-v2/issues/2551

- it should have the "Actions" drop-down menu instead of this big verify your project button
- if the project is verified, we should hide the "verify your project" button in the drop-down (should have a condition where we only show that action if the project is not verified)
- need to fix styling on rejected status.. also let's fix the copy... if verification is rejected... let's just have it say "Declined" (it feels less harsh)... and can we make it grey instead of red? @mosaeedi ?

**Comment by laurenluz** [comment]
@MohammadPCh

**Comment by mosaeedi** [comment]
Here is all of the different status for Verification!

**Asset** -> [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3914-113305&mode=design&t=HUDauAsSKZUdW5HA-4)

<img width="726" alt="Screenshot 2023-07-13 at 1 02 43 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/ed37b17b-87dc-4e87-8f3d-cf08144d7e9e">

### Note:
I changed the colors a bit. I used Gray for **Not verified** status and then yellow for Declined, the red was too much, but still we need something more prominent than the gray to make sure that the users is going to notice it.

**Comment by mosaeedi** [comment]
@MohammadPCh I'm working on the tooltips.

**Comment by laurenluz** [comment]
@MohammadPCh @mosaeedi - I wrote the tooltips in [figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3843-112854&mode=design&t=kS7p5FGXIQoyaQRp-4)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/f806366b-220f-4764-893a-5e7238fd0c00)

**Comment by mosaeedi** [comment]
@MohammadPCh you can find all tooltips here -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3928-114707&mode=design&t=HUDauAsSKZUdW5HA-4)
