### ISSUE TITLE
QF - Improve sorting for QF rounds

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2942]
We should improve the sorting on QF rounds to accomodate QF rounds. So on the QF page, it would be great to sort by:

- "$ Raised this QF round" - this sorts the projects according to the total funding they raised in the current QF round

is that title too long? @MohammadPCh

**Comment by divine-comedian** [comment]
This needs to implemented on the back-end first and then we can update the front-end

**Comment by laurenluz** [comment]
Should add:
- Sort by amount donated in this QF round

@CarlosQ96 - can you work on the backend this week?

**Comment by CarlosQ96** [comment]
Ill leave a pr for this tomorrow. Joining the view

**Comment by MoeNick** [comment]
Can you update us on this issue @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
Hey added the filters and added some tests. However it's getting conflict in database results when executing due to many tables we query at the same time.

Trying to avoid a big rewrite. But seems limitation of the db framework. Spent many hours on it today, will try a few more things tomorrow and update this issue properly.

**Comment by MoeNick** [comment]
@mohammadranjbarz and @CarlosQ96 may meet about it.

**Comment by laurenluz** [comment]
@CarlosQ96 - you're working on this this week, right? would be nice to have before the Optimism round starts (which might be as early as Oct 4)

**Comment by CarlosQ96** [comment]
Yeah i should be done between today and friday, working on a new table that has the current round sums and data.

**Comment by maryjaf** [comment]
Should this issue be implemented for optimism round ? @laurenluz @CarlosQ96

**Comment by CarlosQ96** [comment]
https://github.com/Giveth/impact-graph/pull/1137

**Comment by laurenluz** [comment]
> Should this issue be implemented for optimism round ? @laurenluz @CarlosQ96

@maryjaf - yes please! let's test it :)

**Comment by maryjaf** [comment]
It hasn't been merged, I'll test it with high priority when it will be ready for testing

**Comment by CarlosQ96** [comment]
Ok Found the bug ill push hotfix

**Comment by CarlosQ96** [comment]
pushed hotfix , issue corrected.

**Comment by maryjaf** [comment]
It seems sth is wrong , by setting "Amount Raised in QF" the projects with 0 amount raised are shown in the first position
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da12ff67f68359a72eeb887711afedfb5160e1e4/image.png)
@CarlosQ96

**Comment by maryjaf** [comment]
> It seems sth is wrong , by setting "Amount Raised in QF" the projects with 0 amount raised are shown in the first position

Thanks @CarlosQ96 This problem has been resolve
Plz check the below pic 
The estimated matching for "Test nation" that has 1.93$ is lower than "Giveth" that it has 1.8$ 
I think this problem isn't related to sorting, because sorting based on $ raised in a round is ok , but it seems there is a problem in estimated mating calculation

<img width="1438" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f3a94c8c-c766-41db-8ba4-c75f82dc495a">
