### ISSUE TITLE
GIVbacks on Optimism: Deploy a relayer to distribute GIVbacks to more than 30 addresses

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2987]
As discussed in last week's GIVeconomy call, we'll need to deploy a relayer in order to handle GIVbacks effectively.

@divine-comedian - can you work with @sembrestels or @paxthemax to get this done?

**Comment by divine-comedian** [comment]
Oh! I made an issue here actually:
https://github.com/Giveth/giveth-dapps-v2/issues/2980

The GIVbacks Relayer has already been deploy to OP goerli - I need to work with @sembrestels to make some changes to EVMcrispr so we can use it there, same as we do with current GIVbacks - otherwise it can be a big pain in the butt to work with.

**Comment by laurenluz** [comment]
oop sorry for the redundant issue, I'm going to paste your comment in the other issue and close this one
