### ISSUE TITLE
Notify reward bots for GIVpower on Optimism & Gnosis

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2988]
We need to make a notify reward bot for rewards on Optimism.
Also, we need to adjust our existing notify reward bot for Gnosis because we are taking 10% of the rewards away from the launch time of GIVpower on Optimism.

I set up [this spreadsheet](https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit#gid=1038166692) w/ the amount of rewards that need to go out on each chain for every remaining round, assuming we start this program on August 8. (check the 2nd tab)

@mohammadranjbarz @aminlatifi - once we confirm the launch date for GIVpower on Optimism, can you help to set this up?

cc @moenick

**Comment by mohammadranjbarz** [comment]
> We need to make a notify reward bot for rewards on Optimism. Also, we need to adjust our existing notify reward bot for Gnosis because we are taking 10% of the rewards away from the launch time of GIVpower on Optimism.
> 
> I set up [this spreadsheet](https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit#gid=1038166692) w/ the amount of rewards that need to go out on each chain for every remaining round, assuming we start this program on August 8. (check the 2nd tab)
> 
> @mohammadranjbarz @aminlatifi - once we confirm the launch date for GIVpower on Optimism, can you help to set this up?
> 
> cc @MoeNick

@laurenluz  Do we need to send reward on Optimism-Goerli(for development ENV) as well or Optimism-mainnet in production ENV is enough?

**Comment by aminlatifi** [comment]
> @mohammadranjbarz - do we have test GIV (like DRGIV?) on optimism Goerli that we can test with ? cc @divine-comedian
> 
> I think we should definitely so a test run for development env before setting it up on Optimism Mainnet.
> 
> Also, from what @MoeNick tells me, we won't be able to launch by August 8... so then we must adjust the numbers in the spreadsheet and launch 2 weeks later on August 22 🤔 Am I right, @aminlatifi ?
> 
> I thinking that we have rewards go out every 2 weeks.. so in order to accomodate the changes we have to make on gnosis & the rewards we'll have left on Optimism we need to launch at the start of some GIVbacks round.

Yes, we have deployed test GIV on OP-Goerli. I had deployed it, but now transferred it's ownership to `0xe1ce7720f9b434ec98382f776e5C3A48C8BA6673` CC @divine-comedian 

I agree to test it first on the test env. Probably we need to simulate with the same 2 week duration round period as UnipoolGivpower round duration is 2 weeks. @laurenluz Yes, makes sense.

**Comment by aminlatifi** [comment]
@laurenluz Mohammad and I have discussed how to implement it and reached a good solution.
As a context, on each notify reward script we have these two parameters
- Total Reward: Total Reward will be paid on all rounds, 13M already set to be paid on the Gnosis
- Distribution: The percentage of reward must be paid on each round, [579, 600, 621, 642, 662, 683, 704, 725, 745, 766, 787, 808, 828, 850] already set to be paid (divide each to 100 to get Percentage)
- InitTime: already set 1681840800; // Timestamp of the first round in seconds: Tuesday, April 18, 2023 18:00:00 GMT

Our solution:
### Gnosis ###
Keep all the parameters as it is, except 
- Total Reward:  We will reduce it by 10%, so on all next notify rewards we will charge it 10% less than what was expected and save it for Optimism. So the `Total Reward` on Gonsis will be 11.7M GIV

### Optimism ###
We will set the `Initial Time` as is for Gnosis in order to the start of rounds aligns with each other on all chains. For other values
- Total Reward: Will be 10% of the original value we deducted from the original value. So it will be 1.3M GIV on optimism
- Distribution: It will have zero value for past rounds and will hold the same values as Gnosis one for leading rounds. So, if we want to start on August 22, the distribution on OP will be [0, 0, 0, 0, 0, 0, 0, 0, 0, 766, 787, 808, 828, 850]. In this way we can setup script cron job sooner and don't be worried of being charged before start time.

Note: On OP Goerli test we can launch on August 8, in this case, the op-goerli distribution will be like production but will have positive distribution percentage for round 9 (starts Agust 8). That will be [0, 0, 0, 0, 0, 0, 0, 0, 745, 766, 787, 808, 828, 850]

**Comment by MoeNick** [comment]
can we plan it for next week for GIVeconomy? 
@aminlatifi @mohammadranjbarz ?

**Comment by MoeNick** [comment]
I tagged the currant spront ends up to Aug29. So we have time to test until Sep 6.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
As we postponed ading Optimism for two rounds I changed the Lauren's numbers on this sheet
https://docs.google.com/spreadsheets/d/1hfICAE4rA3az9XVj6nxOD1GTrKAp0SbiNrq5Qi0syZ4/edit?usp=sharing

**Comment by laurenluz** [comment]
@mohammadranjbarz - did you change the notify reward bot on Gnosis (i.e. reduce the numbers) to compensate for the rewards going out on Optimisim?

**Comment by MoeNick** [comment]
I re-checked with Amin and he confimred they did it.
