### ISSUE TITLE
Incorrect message by selecting Draft project 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3082]
**Describe the bug**
By tapping on a project with Draft status in my projects I see the below pic for about 1 second

**To Reproduce**

1. Go to 'my projects' 
2. Click on 'a draft project'
3.see error

this problem also happens after taping on preview at the end of creation order flow

**Expected behavior**
this message shouldn't be shown because this project isn't cancelled
Oops! This project is no longer available or not found!

**Screenshots**
<img width="1361" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dc7e2f5c-e7f0-447d-9ee9-247d9595bf7e">

@divine-comedian @MohammadPCh

**Comment by RamRamez** [comment]
User tokens are needed to fetch draft projects from the backend. In the front-end, we fetch projects server-side for SEO and optimization reasons. The problem is we can't fetch draft projects server side.
First solution: I can fetch all projects on the client side and add a loader for draft projects, but **I don't recommend it**because we lose lots of benefits and gain a loader for draft projects only.

Second solution: Fetching projects server side to keep SEO benefits, but don't show them to the user. Showing a loader, then fetching projects again on the client side, then showing normal project or draft project to the user.
**I don't recommend this solution either**, because it adds single project view loading time.

@MoeNick @divine-comedian If this issue is not that much important, it's better to skip it and not sacrifice single project view load time and SEO.

**Comment by divine-comedian** [comment]
I don't think this is a big enough of a bug to make it worth it, we can icebox this one and work on other things i think.
