### ISSUE TITLE
Donation and GIVbacks issues with my donations to Crypto Commons Association.

### ISSUE THREAD

**Issue by MLBinWA** [Giveth/giveth-dapps-v2#327]
Hello,

I intended to donate 1 ETH to Crypto Commons Association.  I sent .51 twice by accident.  I sent .49 ETH not knowing I had sent .51 ETH twice.  Crypto Commons Association sent back .51 ETH so my donation was the 1 ETH I meant to donate.

I have tried to claim the GIVbacks yet the system doesn't say I can get any.  It also has both .51 ETH donations along with the .49 donation.  The total donation should be 1 ETH.

Can you help me understand what needs to happen in order to correct the system and get the GIVbacks?

Let me know if you need more information.

Sincerely,

Matthew Bonnstetter

MatthewLB@aol.com

**Comment by MLBinWA** [comment]
Hello,
I did see some GIVbacks in my account.  It was just short of $300.  My donation was 1 ETH after the .51 that I sent by mistake since I didn't know the first .51 had gone through was sent back.
So, this was around 10% back.  Is that what was paid during this round?  I had heard that up to 80% could be paid back.
I did stake what was given back and wishing you all the best for the great things you are doing.
Sincerely,
Matthew Bonnstetter


-----Original Message-----

**Comment by laurenluz** [comment]
Your GIVbacks include some part liquid and some part that is added to your GIVstream flowrate. You can learn more about the way GIVbacks is calculated in our docs: https://docs.giveth.io/giveconomy/givbacks#getting-givbacks

Your GIVbacks liquid portion right now would be something close to 10% of your donation value at the time of donation, with the amount of GIV distributed determined using the price of GIV at the time of distribution.

It's a little confusing to explain the way it is calculated. This "80%" maximum that you heard of (which is actually 75%) is actually a factor that is used to calculate your total GIVbacks amount... but the amount you get liquid would be much less that that because about 85% of that is going into your GIVstream... TBH it's a very confusing number and I personally encourage people not to use it when explaining GIVbacks because it ends up being misleading.

It sounds like your GIVbacks amount is actually correct though :)
