### ISSUE TITLE
Bug - On Polygon, it shows I have 0 USDC but I have LOTS

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3277]
I have a lot of USDC on Polygon. our UI, when I'm connected to polygon says I have 0 available.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3ovIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33dd6a1ec9ae8b6bb53d23e5eef900db915de265/image.png)

cc @divine-comedian

**Comment by laurenluz** [comment]
WOW and actually, when I try to donate USDC via staging, it says I don't have enough funds! but I have LOTS!

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/bb332934-b8ad-4712-850e-82e2e51e51a1)

worth noting... it did allow me to donate on production despite the "0 available" thing... the tx opened in metamask and the donation went though

Maybe @MohammadPCh - could you have a look?

**Comment by divine-comedian** [comment]
I think I found the cause of the bug - it looks like it is related to the use of ethersJS on production. The same was happening with USDT which I think @GriffGreen reported in #2600 

It appears the problem is fixed when we made the switch to wagmi - assuming we push to production these changes by friday it should resolve itself... 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ba4d3ffd-0e8b-4eef-b165-ca0c34b10998)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/89984507-f9e5-4caa-b61d-fd8007e33591)
