### ISSUE TITLE
We should make it impossible to have projects "eligible for matching" if they are not raising funds on the eligible chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3279]
[this project](https://staging.giveth.io/project/giveth-tour-bridge-the-world) on staging is "eligible for matching"... but we only have Optimism chain as eligible... but they're not raising funds on Optimism... only Goerli & Gnosis...

SO, this is very confusing for the user!

In our Optimism round, we should take care to ensure that projects in the round all have Optimism addresses... but I think we should also build some flow into admin bro where you *can't* add projects to a round if they don't have a recipient address on the eligible chains for the round.

wdyt @maryjaf @WhyldWanderer ?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajMvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d0a18e0f7123cf4566eb18acba7d3d503f509c2/image.png)

cc @MoeNick

**Comment by laurenluz** [comment]
this doesn't have to be mandatory to build for the Optimism QF round, though it would be nice if we could

**Comment by maryjaf** [comment]
Because the number of projects that have OP on stg was less than 150 and in order to be able to test the addition of a large number of projects for the round.
The projects that have Gnosis or OP were added to the round with the db query 
On production, we can set only the projects that must have OP to be added to the round

**Comment by laurenluz** [comment]
oh that's great!
