### ISSUE TITLE
I just donated to a project, but it tells me the "raised amount" is $0 on the donation page - bummer

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3311]
<img width="960" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2e406c5f-2078-42d8-aa36-f562374ce7d1">

See the "raised" on the left? I think we should just delete this field from the donation confirmatino page...

**Comment by MoeNick** [comment]
@MohammadPCh jumped to it

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Do we update the `total donations` immediately after the donation succeeds?

**Comment by laurenluz** [comment]
I think what is happening is that there is a delay in updating that value while out backend fetches/processes the donation... I think it has to do with verifying the donation on-chain...

but still! I, as a user, when I see that I donated, and this little $0, it feels really strange. I feel like we could just hide if from the frontend and not worry about the backend delay

**Comment by MohammadPCh** [comment]
@laurenluz Thanks. Maybe it's nice to consider it in the new design of the donate page. @mosaeedi

**Comment by divine-comedian** [comment]
@MohammadPCh - Can we follow up on this one as we do the SF release, which includes updates to these cards?

**Comment by MohammadPCh** [comment]
@laurenluz @divine-comedian Since it takes time for the transaction to be confirmed by the network, we cannot ensure its immediate fix. I believe the solution is to either remove it from the success page or add it manually. However, manual addition might be unstable, as the transaction could be confirmed by the blockchain soon after. This could result in inaccurate values being added again. What do you think?

**Comment by divine-comedian** [comment]
@MohammadPCh - let's remove it then, just from the success page view.

**Comment by maryjaf** [comment]
"rasided" has been removed from success donation page
