### ISSUE TITLE
WC Testing: iPhone/Safari MOBILE | Trust Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3332]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by maryjaf** [comment]
- [ ]  There is no "Trust wallet" option when user taps on "sign with solana" on mobile
@divine-comedian 

https://github.com/user-attachments/assets/fbc6a3db-a68e-48c5-9b36-e6ab8f57f8ca

**Comment by divine-comedian** [comment]
Thanks MJ - After some consideration let's remove Solana connections as a requirement for this feature, if everything else is approved let's move it to done.

**Comment by kkatusic** [comment]
> @MohammadPCh - I think we need to add Trust Wallet to the options available from the wallet adapter menu

I put Trust wallet adapter for Solana network but it don't offer Trust Mobile/Desktop option like it is enabled on wagmi and web3modal package option:

![Screenshot 2024-08-20 at 15 28 51](https://github.com/user-attachments/assets/43c9d9c9-160a-46d2-9756-2e9a7ce63838)

also tried this to enable by adding Wallet Connect adapter but it didn't work using Trust or Coinbase mobile wallet.

Will do research, because to add adapters it is only one additional variable inside network connection definition.
