### ISSUE TITLE
Allow users to return to the same position while going back & forth on the project details / all projects list

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3417]
From #910 

We should allow users to go back and forth between viewing project single page & returning to the all projects list or a saved filtered list to be returned to the place in the scrollable page where that project card was located. 

> 
> it would be cool if when I am on a project page and I hit the back button to go back to the projects page that:
> 
> * the same filters/sorting, if any, is applied as before
> * I am taken back to the part of the page where the project I last clicked on was located.

For example if I scroll through 1/2 to the bottom of the page - select a project to view and then go back I should be returned to that same position I left off at - 1/2 to the bottom of the page, or wherver it was that the project I clicked on was located at in the list. 

This means that if a user is browsing amongst a large list of a projects everytime time they want to view a project in detail and go back to the main list they don't have to start at the top of a long list of projects they have already seen.

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/776f916b-5f50-4552-b217-e8b83790604e

**Comment by jainkrati** [comment]
@kkatusic pls take this up

**Comment by kkatusic** [comment]
@divine-comedian , I gave my yesterday morning, today afternoon on this issue, just to clarify some behaviors. On your example on Amazon website they have pagination and if you click on back it will always return you to the scroll place that you stop before you have been clicked on some product, it is same if you open some news portal and click on some article on the middle of page and then turn back again it will take you to the middle of the website.
That's browser behavior, better example is twitter website.

I tried do this on giv projects page, done some saving state about current page that you load, what project you clicked and when you turn back to load all project that you viewed, but having issue with maximal projects that can be fetch on the api side, it is 50. Than tried to put some loop and fetch data, but isn't best solution and than stuck. Next solution is rearrange all component, logic on that page, but don't know how to do that on right way because this page is on of the crucial for Giveth.

Need to ask someone smarter than me what is best practice to manage this, Cherik is ultra busy, but I will find someone who can help me.

Just small update about this ;)

**Comment by divine-comedian** [comment]
Sure! I think @alireza-sharifpour @RamRamez and @mateodaza are all qualified individuals for you to ask.

**Comment by MohammadPCh** [comment]
@kkatusic maybe this helps you: https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries

**Comment by maryjaf** [comment]
Thanks @kkatusic it works as expected

**Comment by kkatusic** [comment]
> Thanks @kkatusic it works as expected

big thx @MohammadPCh for all help
