### ISSUE TITLE
Add Coinbase Wallet to web3Modal

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3446]
Add in support for Coinbase Wallet for users to login and use the dApp
https://walletconnect.com/explorer/coinbase-wallet

We will need to thoroughly test all cases & app functions - Test cases are contained in the following issues: 

- #3321 
- #3324 
- #3327 
- #3330 
- #3333
- #4555

**Comment by MohammadPCh** [comment]
@divine-comedian We now have the Trust Wallet! Should we pass it to QA, or is there a bug we need to address first?

**Comment by MohammadPCh** [comment]
@kkatusic @lovelgeorge99 Which of you has the bandwidth to handle this?

**Comment by kkatusic** [comment]
> @kkatusic @lovelgeorge99 Which of you has the bandwidth to handle this? Feel free to assign it to yourself.

I will take it, thx @MohammadPCh

**Comment by kkatusic** [comment]
@divine-comedian, let's be consistent

The following test cases should be completed and successful:

 - [ ] Sign in
 - [ ] Switch Network (from navbar dropdown menu)
 - [ ] Switch Network (from givfarm)
 - [ ] Connect Wallet(from GIVfarm/GIVback)
 - [ ] Connect Wallet and sign in (from passport banner)
 - [ ] Switch network (from donate page)
 - [ ] Donate ERC20
 - [ ] Donate native token
 - [ ] Stake GIV
 - [ ] Lock GIV
 - [ ] Unstake GIV
 - [ ] Harvest rewards (GIVfarm)
 - [ ] claim GIVbacks
 - [ ] claim GIVstream
 - [ ] Connect with Multisig
 - [ ] Create recurring donation
 - [ ] modify recurring donation
 - [ ] deposit/withdraw from stream balance
 - [ ] end recurring donation
 - [ ] Donate SOL
 - [ ] Donate Solana Token

**Comment by divine-comedian** [comment]
@kkatusic - we'll need to test on several different browsers and devices - here's an example https://github.com/Giveth/giveth-dapps-v2/issues/3445#issuecomment-2260644272

When the integration is ready we can work on the test case issues.

**Comment by kkatusic** [comment]
@divine-comedian I need to test these all cases? Not problem but how to test with iPhone if I don't have it? thx

**Comment by kkatusic** [comment]
@divine-comedian, update about Solana donation:

- tried donation on staging but it doesn't work:

![Screenshot 2024-08-09 at 14 39 42](https://github.com/user-attachments/assets/7dc94b4e-9cd4-4b1e-9a1c-12016ad7dfd2)

there wasn't any errors inside console logs, talked with @RamRamez and he point that error is happening on FE. Than I tried to use Phantom wallet on staging and got same error. 

Done some investigation and found that sometimes transaction `feePayer`has _undefined_ value, searchedd solution and found some solution if it doesn't work add current user wallet key to it. After that on Phantom wallet donation was working, but on Coinbase same. 

- tried donation with Coinbase on production setup and it is working:

![Screenshot 2024-08-11 at 17 13 29](https://github.com/user-attachments/assets/da109f92-9a26-48a5-b058-86d3b797613a)

and my questions are, if I introduce hotfix will Phantom work on production and will we investigate this further more because I can't find any other errors, maybe someone else can check this? My opinion is that we will lost time on this, when finding solution for payer fee I found posts 2 years old, maybe they didn't fixed that using devnet solana network

**Comment by divine-comedian** [comment]
i'm okay with it not working for solana devnet since as you have shown it appears to work on production.

**Comment by divine-comedian** [comment]
@kkatusic when this is ready to test on staging please let me know to assign testers based on issues I've tagged above in the original issue description

**Comment by kkatusic** [comment]
> i'm okay with it not working for solana devnet since as you have shown it appears to work on production.

Ok, thx

**Comment by kkatusic** [comment]
> @kkatusic when this is ready to test on staging please let me know so I can assign testers based on issues I've tagged above in the original issue description

I requested review of PR, will let you know when it is approved

**Comment by kkatusic** [comment]
@divine-comedian took some time in the the evening to check again why test solana doesn't work on coinbase wallet, didn't find solution, no errors in console. As I can see sometimes gas fee isn't provided from transaction hash or payer object isn't provided as it should.

Tested with production setup on local host for Solana SOL token:

![Screenshot 2024-08-14 at 10 27 26](https://github.com/user-attachments/assets/57230d74-3c47-4aa7-93d7-b6630d67ab45)

and transaction TX:

https://explorer.solana.com/tx/41qoRLzwf4SWeZHscahh5uUQMaPZDshd5anYskxWuj6v9w4BUuxZfZ9SraqVqNkoNPqTwBQGkMhprJXXLSaXAgys

have problem with RAY token donation on Solana, fix will come soon:

![Screenshot 2024-08-14 at 10 47 19](https://github.com/user-attachments/assets/5de1b19a-6d99-4b1b-95c8-f38d41a26431)

and transaction TX:

https://explorer.solana.com/tx/cmW5bYh9gxvdZZkMvJKarSQb67JhCXRqQfyu2j8Z16Y6MbM6MvxirZ1MsWZDekhAKTDPckf5XxPFcVxX7DHMtHX

**Comment by divine-comedian** [comment]
@kkatusic since we removed solana from requirements should we close the open PR associated with this issue?

**Comment by kkatusic** [comment]
> @kkatusic since we removed solana from requirements should we close the open PR associated with this issue?

Yes, like you said we have removed from solana support for coinbase wallet. You can close it, thx
