### ISSUE TITLE
Big bundle size

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3603]
The production page is loaded so slowly since we have a JS bundle bigger than 1MB size.

<img width="1124" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/5684607/cbe28074-f529-4ec9-bf33-617c4457bcb1">

https://giveth.io/_next/static/chunks/pages/_app-7b7ed37c11059ff3.js

Is it possible to improve it? split it to smaller ones or reduce its size?

**Comment by MohammadPCh** [comment]
@aminlatifi Thanks for creating this issue. As you can see, the most-sized bundle is `_app-e7197....js`.
<img width="780" alt="Screenshot 2024-02-06 at 9 03 34 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/93b35b85-c400-4635-bda1-aaebab2a3d9b">
<img width="716" alt="Screenshot 2024-02-06 at 9 06 21 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/0c799725-47d1-4a16-9b90-81c3c8cfabc9">
Unfortunately, we cannot identify any valuable components to remove from this bundle. If there are specific elements you think we could optimize, please let me know.

**Comment by aminlatifi** [comment]
Thanks @MohammadPCh for preparing this fancy schema. Why do we have _app.tsx while we have index.under ui/dist/esm?

**Comment by aminlatifi** [comment]
Also, I see design system takes large space. Checked the `next` dependency version on its repo and dapp repo, they are not the same. Do you think synching their version will reduce the bundle size by not having two version of next?

**Comment by jainkrati** [comment]
What is the contribution of images in this bundle @MohammadPCh ?

**Comment by MohammadPCh** [comment]
@jainkrati, just to clarify, this bundle map relates to JavaScript files. As for images, we utilize the Next.js package, which I'm sure takes care of lazy loading and other optimizations.

**Comment by MohammadPCh** [comment]
This is the result after we update packages for the DApp and UI-design-system.
<img width="2302" alt="Screenshot 2024-03-12 at 11 05 11 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/f110898d-8f1e-4d51-8e67-b9d8d08f32a3">
and this is for our main js:
<img width="1144" alt="Screenshot 2024-03-12 at 11 08 10 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/2b5e5fc0-34d4-4c78-95f6-bc9e0720f71c">
as you can see there are some opportunities to optimize our app:
1. using superfluid contract instead of its SDK.
2. remove lottie package and use simple CSS animations.
but both of them may decrease user experience quality.
