### ISSUE TITLE
Save Donation bug

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3604]
From brichis [in discord](https://discord.com/channels/679428761438912522/1187124227468435536/1194698603629912126)

GM! I had an issue today while donating. I donated and the tx was successful but it is not reflected in the project
https://giveth.io/project/semillitas-de-fe-esperanza-y-amor?tab=donations

https://gnosis.blockscout.com/tx/0xe792886f6179716a9bacd17515564283789fb328b6d30bf5c7616f3581ee804f

https://gnosis.blockscout.com/tx/0xc3aef94719ae91b710ff8af4c09b7be754a3a43a669b70955cc3620d0d5714ab

![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/09ac38bc-244c-4b74-b090-a30a40cd5754)![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/7b94cf5d-f776-4caa-8b93-47682037658f)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/c443fd6a-8568-461c-8e30-9de71b3e403c)

**Comment by aminlatifi** [comment]
There is no clue on the backend, only in sentry we have these logs at the donation moment

https://giveth-ds.sentry.io/issues/4787241162/?end=2024-01-10T17%3A39%3A59&project=6292414&query=&referrer=project-issue-stream&start=2024-01-10T17%3A35%3A00&utc=true

If I am not mistaken, user didn't have stable connection at the moment since fetching from both subgraph and impact-graph had failed.

**Comment by aminlatifi** [comment]
@MohammadPCh

**Comment by MoeNick** [comment]
Shall I keep this issue?
