### ISSUE TITLE
Donation bugs on prod 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3628]
**1-** 
after confriming on metamask i got this error
"Your transaction has failed!Please go back and try again."
https://polygonscan.com/tx/0x74197ad35685603263d7b2f38600821f98a2363a8266fddde2c6204f68d698f7

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/08f7412f-02eb-4a10-b380-2d75ee0c0171

<img width="1433" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5a566f6c-bb08-4656-acf5-9d5c6c2a8260">
-------------------------------

**2-** 
showing sign modal again and again- backedd issues 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8588734d-124b-4a94-bc7a-84d7342d217b

cc: @MohammadPCh @mohammadranjbarz @aminlatifi @MoeNick @jainkrati

**Comment by MoeNick** [comment]
Tagging also @CarlosQ96

**Comment by aminlatifi** [comment]
@maryjaf Are you sure you have a stable and free connection? Because I saw you got timeout even from coingecko in the last video.

**Comment by maryjaf** [comment]
My vpn connection is sometimes weak but I'm not sure if these problems are entirely related to my connection or not

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6e6f9cd1-eeb8-4d68-ba43-178c2907f63e

**Comment by aminlatifi** [comment]
> Screen.Recording.2024-01-15.at.6.01.38.PM.mov

In the video, our request to JRPC node made by MetaMask failed which is independent of app reliability. It seems your connection is not in normal mode. BTW, I saw the request to coingecko gets CORS error which must be noticed @MohammadPCh @geleeroyale @mhmdksh

**Comment by mhmdksh** [comment]
Thanks @aminlatifi @MoeNick @maryjaf 

Hey everybody, I've reviewed the above errors here's what I see we have:

1. Socket Error when connecting to wss://relay.walletconnect.org/ 
2. Too many requests to Sentry
3. Errors regarding impact-graph and auth service connectivity Timeout
4. Coingecko CORS Errors. 


And here are my feedbacks on every point:
1. This is a connection error to wallet connect [Not related to our Backend]
2. We are getting a lot of those and the reason is that we have a lot of logs that are going to Sentry, that it is eating up all our quota (1 Month Subscription in 2 days) @geleeroyale Can explain more about this. Maybe we need to revise what we log to Sentry @MoeNick [Not related to our Backend]
3. These errors happened when we were doing live maintenance on production yesterday when we had the donation errors and we discovered a limitation in redis. And this was fixed by modifying our redis caching config [Backend Related]
4. Coingecko seems to not allow our domain ([giveth.io](http://giveth.io/)) from connecting sometimes. @mohammadranjbarz @aminlatifi @CarlosQ96 Can you provide insight on how we are connecting to coingecko? And if there is any restrictions on our domain?? [Not related to our Backend]

**Comment by jainkrati** [comment]
Thanks @mhmdksh , For #2 @CarlosQ96 will be working on https://github.com/Giveth/giveth-dapps-v2/issues/3626. 
For #4, @mohammadranjbarz can you pls take a look.

**Comment by aminlatifi** [comment]
@mhmdksh Regarding 4, we use public coingecko api, totally a frontend functionality.

**Comment by mohammadranjbarz** [comment]
> @mhmdksh Regarding 4, we use public coingecko api, totally a frontend functionality.


We use in backend as well for SOLANA and ETC tokens, but I think they don't have any IP restriction in this public API

https://www.coingecko.com/api/documentation

**Comment by mhmdksh** [comment]
> > @mhmdksh Regarding 4, we use public coingecko api, totally a frontend functionality.
> 
> We use in backend as well for SOLANA and ETC tokens, but I think they don't have any IP restriction in this public API
> 
> https://www.coingecko.com/api/documentation

Hey @mohammadranjbarz thanks for the info, it's written that they have a 30calls/min rate limit in their main page

<img width="1089" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/52987806/eaf08692-2ceb-482c-b1d6-12b6978d3558">

This might contribute to failures sometimes when there is a heavy load for sure

**Comment by mhmdksh** [comment]
But they have a paid plan: https://www.coingecko.com/en/api/pricing

<img width="1361" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/52987806/f2c2390d-0f5e-49bc-b077-fd22b4244652">

**Comment by mohammadranjbarz** [comment]
@mhmdksh  yeah because of that we cache the prices for 1a specific time (it's in config) in backend (for each token)
So I don't know if we received too many requests error or not

**Comment by mhmdksh** [comment]
I would like to assess, what other usages that we have with coingecko API, and I would like to compare their plan with covalent

**Comment by MoeNick** [comment]
Any update on this issue @mohammadranjbarz @mhmdksh 
if we're not spending time on this, let's move it to product backlog.

**Comment by jainkrati** [comment]
@mohammadranjbarz @mhmdksh pls strategise on a way to use the free tier accounts in a round robin fashion. Invite me if you need

**Comment by mohammadranjbarz** [comment]
@jainkrati @mhmdksh  @MohammadPCh 
As we have mentioned in the above comments, it's not related to the backend, it's failing when the frontend tries to get price from Coingecko itself anyway Coingecko rate limit would not make a problem because in the front they just get the price once during donation flow. ( But if we are still concern about it we can change frontend to get the price from backend, and cache the prices in the backend to not get any error)
WDYT?

**Comment by jainkrati** [comment]
yes @mohammadranjbarz this is exactly what we need : " we can change frontend to get the price from backend, and cache the prices in the backend to not get any error" but two more things here: 
1. BE should cache prices only for 4 hours and then refetch
2. BE should use multiple RPC Api free accounts in a round robin fashion when fetching prices for step #1.

**Comment by jainkrati** [comment]
this seems related to Toekn price fetching logic https://github.com/Giveth/impact-graph/issues/1238, so assigning @aminlatifi as he is working on previous one.
