### ISSUE TITLE
Add mpETH as a donation token on Giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3639]
We are preparing to run a QF round in [partnership with MetaPool](https://www.notion.so/giveth/bd1a4bd498004824b161b81bebf2a995?v=155115c4a54c4285b82c7dc283ed4cc1)

and they are requesting that we make it possible to donate mpETH in the round.

would like to add mpETH as a donation token on Optimism & Mainnet:
- https://optimistic.etherscan.io/token/0x819845b60a192167ed1139040b4f8eca31834f27
- https://etherscan.io/address/0x48AFbBd342F64EF8a9Ab1C143719b63C2AD81710

Should be GIVbacks eligible... I think we can just use the mainnet price oracle for GIVbacks, and make it GIVbacks eligible on both mainnet & OP - checked with @GriffGreen 

On Mainnet, I checked cowswap and you can buy $10k without moving the price more than 2%:
<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6d391371cf4869484ba68189d3e3313488940d2/image.png" alt="image.png" />

It would be great to have this ready by the end of Jan! or at the very least, it needs to be up by Feb 12.

cc @jainkrati @divine-comedian

**Comment by divine-comedian** [comment]
I can add it into the dapp but we'll need to make sure we handle zee prices 

@CarlosQ96 - can I work with you on this one? 

After that we'll need to test a donation 

@laurenluz - do you have a clean PNG image of the token logo?

**Comment by laurenluz** [comment]
https://drive.google.com/drive/folders/1L2GxVMjzJ5RfJ-uQeAlwAEoB3JCpNW5E

**Comment by MoeNick** [comment]
I added this to Metapool Epic https://github.com/Giveth/Roadmap/issues/101

**Comment by divine-comedian** [comment]
Talked to some devs 

So for the front-end price fetching to work metapool will need to add their token to coingecko 

On the back-end we need to add mpETH to monoswap 

@jainkrati who can take this one?

**Comment by jainkrati** [comment]
I wil get back on this.

**Comment by MoeNick** [comment]
Can we set priorities to this one, as teh round is near I assume It's P1 but next week it will be p0. right? @divine-comedian @laurenluz

**Comment by jainkrati** [comment]
@CarlosQ96  and @mateodaza can you take this up for BE and FE side research and tasks.

**Comment by maryjaf** [comment]
I'v check changes of this pull request and it seems, it cannot be tested on a test network, am i right? @CarlosQ96

**Comment by jainkrati** [comment]
We can make a hotfix to test it

**Comment by CarlosQ96** [comment]
ok ill make a release

**Comment by maryjaf** [comment]
Thanks @CarlosQ96  
I've checked and these new tokens are added in token list on op an eth and I could complete a success donation with Metapool token on op
but two item should be fixed in UI 
- token's icon  and USD value  should be shown correctly

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjQyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b9c4e6d682aad79c0fe49d5e3da5b68a9661a29/image.png" alt="image.png" />

<img width="1603" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjgyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--375d0470d59c5eb72378e8bf375f4557107cf3e6/image.png" alt="image.png" />


<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmsyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a68d9fef523e70e75103e4db766e48a7a943e589/image.png" alt="image.png" />

**Comment by jainkrati** [comment]
@maryjaf to close on this and list FE issues if any

**Comment by MoeNick** [comment]
@mateodaza would you pls take a look?

**Comment by mateodaza** [comment]
[PR](https://github.com/Giveth/giveth-dapps-v2/pull/3737) Related solving the price issue on the frontend

**Comment by maryjaf** [comment]
mEth token couldn't be tested on stg, after deploy on prod let me know to check please @mateodaza
