### ISSUE TITLE
Change link on "Learn more" when user pastes a token contract address

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3696]
when i paste a token contract address, I get this message: 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/968eac3e-7441-4e04-9ee3-2b914850724d)

but the link goes to the giveth docs for givbacks, where it is hard to find the link to the forum. We can streamline this by linking direct to the forum:https://forum.giveth.io/t/givbacks-token-list/253/

this request came from a user in our discord support channel.

cc @divine-comedian

**Comment by divine-comedian** [comment]
Ah, apparently the link was there this whole time! It just wasnt highlighted very well so you couldn't tell it was a link, I made it bold to help make it more clear, changing the Learn More link is a bit more complicated since it is static and does not change depending on the status of the token. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/eb80992b-5a00-404e-90f1-323ac1b1cc6e)
