### ISSUE TITLE
Show QF warning modal when Donate button is pressed on the projects page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3874]
Today when I was looking at the QF page.. I noticed that there is now a warning modal to let users know that the round hasnt started yet. This is really great and will most likely prevent the user confusion we experienced during polygon round.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/b34205c9-a141-4a33-8e27-06a9179d3406)

Can we also show this modal when the donate button is pressed on the Project's page donations tab?
When I view the QF Round tab under 'Donations' it says "Be the first to donate in this round!" but when I click it there is no indication that the round has not yet started.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/e29063a5-19ac-40bb-a37a-e40abcc6d6ce)

**Comment by WhyldWanderer** [comment]
cc @laurenluz

**Comment by laurenluz** [comment]
@jainkrati can you help to assign the right person to give feedback on if this is possible?

I'm not sure if we are checking, for example... from where the user clicks "donate" and/or if there is something in the backend we can use to tell the frontend the user clicked donate from the upcoming QF round tab. so that we could show the modal in this case (and not in other cases of clicking "donate" from other places).

I hope that made sense 😵
