### ISSUE TITLE
Get contact information from projects in the verification form

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3910]
We should add new optional fields to the project verification form that allows us to DM them if needed on other platforms. 

In the project verification UI we will need fields for:

telegram
discord
twitter handle
whatsApp

@divine-comedian @WhyldWanderer anything else?

We need to collect this info so we can do better outreach around marketing initiatives like QF etc.

back-end related issue is https://github.com/Giveth/impact-graph/issues/1436

**Comment by laurenluz** [comment]
I think this is at least a P2. Without having this contact info, the comms team & outreach folks end up doing way more working running around to get it, we've wasted a lot of our contributors' time because we don't have this readily available. This should be a "normal to do" thing... we need it.

**Comment by laurenluz** [comment]
should we close this issus? I think it's redundant w/ the one in impact graph

**Comment by divine-comedian** [comment]
No because this one is a front-end issue - we'll need the design space put into the verification form - the other one is related to saving information into the back-end & making it available in adminJS.

**Comment by Tosinolawale** [comment]
![Project contact](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/1d005c6c-29d1-4939-a953-6e72863befe9)
@laurenluz @divine-comedian 
https://www.figma.com/file/WCfheR8ID8yqNglhW1ZeM0/Project-Verification?type=design&node-id=6120%3A9383&mode=design&t=lQTSqn1b4Nte5saw-1

**Comment by divine-comedian** [comment]
@Tosinolawale 

Just those 4 fields - you can remove things like website, youtube, instagram

We're looking for user handles not URLs so the default text in the input field should reflect that.

**Comment by Tosinolawale** [comment]
![Project contact](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/decbb498-6103-4d9e-86be-f2600813915a)
https://www.figma.com/file/WCfheR8ID8yqNglhW1ZeM0/Project-Verification?type=design&node-id=6120%3A9383&mode=design&t=E2QzqsiBBOhChcZP-1
@divine-comedian

**Comment by divine-comedian** [comment]
@jainkrati  - Could you assign an FE dev when time permits for this one? This is adding the FE component to the project verification form - it will need some BE changes in order for the info from the form to be saved to the back-end https://github.com/Giveth/impact-graph/issues/1436

**Comment by WhyldWanderer** [comment]
I think the idea here is to collect the contact information of the project owner. By putting these fields in the "Project Social Media" section, it indicates that the person filling out the information for the project and not the project owner. They will tend to add the projects TG froup rather than their personal TG handle. 

Is it possible to have these fields in the "Personal Info" section instead?

I believe this data is pulled from the owners profile, Maybe it makes more sense to add these fields into the profile creation flow and we could also pull it from there? 

Im not sure which option is best.. on one hand if we put it in the profile creation flow, the user might be less likely to add it but if they are filling out an application they will want to provide more info... whichever we choose, we should make it clear that these fields are for personal contact info and not project information.

**Comment by laurenluz** [comment]
Rather than making further changes to the verification application... can we just add a "add your personal tg for the project owner" field in the "create a project" page...

I think this should just be a separate issue. It's not redunant with this... as this is asking for project socials and is totally reasonable as it is.

**Comment by divine-comedian** [comment]
@laurenluz @WhyldWanderer 
The problem is that using this section of fields as adding a project social media profiles is redundant with the feature on the project creation flow where they can add their social profiles. It's confusing to ask them twice for their social media profiles

Currently... 
### Project Verification
![Screenshot from 2024-04-30 10-54-03](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/249983ac-69db-4c93-846a-011bb1bbf995)

### Project Creation
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2e781345-dc6f-4e99-81f5-6fb07425957c)

----

We can add an option for the user to add a TG group to their social media profiles on project creation/edit

If we change the copy of the project verification form to ask for their contact info as the project owner it would create the least amount of changes.

**Comment by laurenluz** [comment]
there is a distinct difference between "your project tg group"... used publicly to allow donors & other users to join the community & see what the project is up to.

And "the project owner's personal tg" ... used to ping internally about important things like "hey! you need to add an arb address if you want to get money in this qf round"

**Comment by laurenluz** [comment]
Ahh sorry. Well I think that's an ok change, though it would be better to grab this info from all projects... rather than only ones that fill out the verification application. The only downside for us is that the changes are a little heavier... but in the long run it will results in us collecting info from all projects we might need it from... rather than a select few....

**Comment by divine-comedian** [comment]
@Meriem-BM 

We'll need bring back this one field:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8f0fd966-ce6e-4834-8c1d-d16570593662)

This is used to allow the project to add a link to where they posted about their Giveth project on one of their social accounts

just above the field it should have this sub-header: 

### Giveth Project Social Link

It should use this internationalization label as the text below the sub-header:

`label.in_order_to_ensure_that_you_are_a_representative`

 then below the sub-header and text add back the missing aforementioned field. 
 
Lastly we should remove the "Add Other" button
