### ISSUE TITLE
Apollo Errors Flooding the frontend (Latency Session Findings)

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/giveth-dapps-v2#4115]
**Describe the bug**
An Apollo Error is flooding the frontend, 75% of the errors in Vercel are apollo errors. It's worth it to take a look
**To Reproduce**
1. Go to giveth.io
2. Browse the projects

**Expected behavior**
Not getting this much errors
**Screenshots**
<img width="1322" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/52987806/5433fca8-31bc-421b-a247-d005c4c63e49">

**Desktop (please complete the following information):**
 - MACOS: Chrome, Brave Browsers
**Additional context**
The error is all over the place, when checking the Vercel Logs, here is a sample copy of the error text:

(node:12) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
An error occurred! For more details, see the full error text at https://go.apollo.dev/c/err#%7B%22version%22%3A%223.9.3%22%2C%22message%22%3A35%2C%22args%22%3A%5B%22%7B%7D%22%5D%7D

For the fix it's clearly stated in the error message with a URL: https://go.apollo.dev/c/err#%7B%22version%22%3A%223.9.3%22%2C%22message%22%3A35%2C%22args%22%3A%5B%22%7B%7D%22%5D%7D

CC: @jainkrati @RamRamez @MohammadPCh

**Comment by mhmdksh** [comment]
**Note:** that browsing the projects with curl through graphql works just fine:
```
curl --location 'https://mainnet.serve.giveth.io/graphql' \
--header 'Content-Type: application/json' \
--data '{"query":"{\n    allProjects(limit : 30) {\n        projects {\n            id\n            slug\n            totalDonations\n            projectPower {\n                totalPower\n            }\n        }\n    }\n}","variables":{}}'
```

**Comment by jainkrati** [comment]
This should get fixed once complete solution of db read replica is implemented by carlos

**Comment by RamRamez** [comment]
@mhmdksh these errors are related to the time that production was unstable, today I checked again and we don't any errors on production on last 24 hours

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/3853c53a-87ac-47fb-9025-847e45d6633f)

on staging we have 28 errors on last 24 hours, that is because staging is not stable at the moment and throwing 500 errors sometimes

<img width="1333" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/73441857/2c54f596-703a-449f-a6fb-7b1f2a01787b">
