### ISSUE TITLE
"Total Raised" does not match "All-time donations received" 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4156]
**Describe the bug**
The Total Raised by a project in an active QF Round is not updating properly.

Example:
https://giveth.io/project/diamante-luz-center-for-regenerative-living-0?tab=donations
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/0b66bb7d-2516-4418-9f63-7353aba1117f)

https://giveth.io/project/pcrf-palestine-childrens-relief-fund?tab=donations
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/b7e80358-da1b-476e-b779-ef74c73522a1)

**Comment by divine-comedian** [comment]
This one is related to us using two different variables from the projectData 

`totalDonations` and `sumDonationValueUsd` 

AFAIK due to our recent issues with refreshing the materialized view the latter variable is not able to update, however totalDonations still is updating 

Shouldn't we use the same variable for everything? If so, which one should be used? @CarlosQ96 @mohammadranjbarz
