### ISSUE TITLE
zkEVM | changes on Donation page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4256]

**Comment by maryjaf** [comment]
- [ ] This address should be added to Giveth project, my donation to Giveth project is failed

**Comment by mohammadranjbarz** [comment]
> * [x]  This network should be added to Giveth project recipient address, my donation to Giveth project is failed

Done.

**Comment by maryjaf** [comment]
This issues has been resolved.

**Comment by maryjaf** [comment]
- [ ] please check the below scenario @mohammadranjbarz 

1- this project has 2 supported network https://staging.giveth.io/donate/testzk
Ethereum classic and zk EVM

2- but in Switch Network modal only Ethereum classic is shown 

I'm not sure this problem is exactly related to this issue or not 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f90527d7-c6e3-418e-bcca-363ca5145239

**Comment by mohammadranjbarz** [comment]
<img width="1213" alt="Screenshot 1403-04-03 at 12 32 07 in the afternoon" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/329e1b42-6a02-4437-878b-976f071b23c6">

@maryjaf  I fixed it

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz this issue has been resolved
