### ISSUE TITLE
Show switch network modal on sign in by default when user is on unrecognized network

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4271]
I went to donate to the matching pool and went to click the sign in button at the top... my metamask was connected to zk sync and i got a really weird screen

![Screenshot 2024-06-12 at 9 16 25 AM](https://github.com/Giveth/giveth-dapps-v2/assets/14945613/03491d19-e844-4cd8-ab01-cc1709e30653)

I would have liked it to ask me to connect to a different network...

**Comment by divine-comedian** [comment]
When the user connects with an unrecognized network we show them a default modal from web3modal, like the one pictured above. Usually the user needs to click the button that has the chainId on it, but this may not be intuitive enough for them to know where to click. 

We do automatically show a clear switch network modal but it can be clicked out of and the user might be lost afterwards

When the user is connected to the wrong network they can click CONNECT WALLET -> sign in splash page -> sign in with Ethereum ->  we should try to show them this modal instead, if they are connected to an unknown network: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/617c2781-9ec5-4d52-ae69-5ecb300b3974)

OR this one: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/b2c49b59-4a62-42b4-83e0-8e7fec77bae7)


We should try to use either of those views and AVOID showing the web3modal view that Griff posted above, since it is pretty unhelpful for the sign in process.

**Comment by MohammadPCh** [comment]
Thanks @GriffGreen @divine-comedian. I've made some improvements. Can you check this link and confirm if the result is as expected? 
https://giveth-dapps-v2-git-fix-unsupported-network-modal-givethio.vercel.app/

**Comment by divine-comedian** [comment]
Tested it out, looks good to me! Let's carry on with bringing this to staging

**Comment by maryjaf** [comment]
- [ ] The switch network option is removed in the below menu @MohammadPCh 

STG:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4d4fde48-5a0a-4531-bd4d-a72253abdcbb)

PROD:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/511065eb-5ee1-42ae-bf2c-4cc74dcfc0e3)

**Comment by maryjaf** [comment]
- [ ] 2- 
- On stg my user is signed and my network is Gnosis 
- I change my network to Op mainnet
- As you can see in below screen record, the Switch Network modal is shown but my user is signed out 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9450c064-3976-43f0-b25a-a86f93213faf

**Comment by divine-comedian** [comment]
@MohammadPCh - please follow up on these reported bugs

**Comment by maryjaf** [comment]
> [x] 1- The switch network option is removed in the below menu @MohammadPCh

Item 1 has been resolved and now "switch network" option  is shown.
Item 2 remains.

**Comment by maryjaf** [comment]
This problem should be checked and fixed before release in this week @divine-comedian @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf What behavior are you expecting? This issue requests displaying the switch network modal instead of the default web3modal, which appears to be functioning correctly. The reason user data is not shown is that the op mainnet is not a valid network.

**Comment by maryjaf** [comment]
> * [ ]  2-
> * On stg my user is signed and my network is Gnosis
> * I change my network to Op mainnet
> * As you can see in below screen record, the Switch Network modal is shown but my user is signed out
> 
>  Screen.Recording.2024-06-27.at.10.17.00.AM.mov

Have you seen this video? my user is signed out in this video  @MohammadPCh 
if this screen record is accepted we could call it Done @divine-comedian

**Comment by maryjaf** [comment]
So user sign out  user by changing the network to an unsupported network is an expected result in this changes


https://github.com/user-attachments/assets/ba6eaba6-b1d5-47f1-9d1c-4a983e317b2f

**Comment by divine-comedian** [comment]
@maryjaf - sorry I tested this out and forgot to respond to you. 

This is acceptable as long as the "choose network" or select network modal is shown it should be intuitive enough for the user 

sign in -> select from an eligible network -> get request to switch network in MM
