### ISSUE TITLE
MyAccount | Overview

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#43]
@MoeNick commented on [Mon Jan 17 2022](https://github.com/Giveth/giveth-io-typescript/issues/69)

[Over View Page Design](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3889%3A104687)

Elements:

- [x] Short Profile Description
- [x] Donations total amount / total count - Amount should be calculated based on the USD value of currant 
- [x] Total projects

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/43?planning-poker) with ZenHub @mateodaza @MohammadPCh @pkretzschmar

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/43?planning-poker) with ZenHub @RamRamez

**Comment by MoeNick** [comment]
Please add this design after user click on copy address,  (the icon in front of user address) 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/82b6c302-f962-496e-8cc9-9283f44a59aa)
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2121%3A61706

**Comment by MoeNick** [comment]
- [ ] My account - Overview | No donation / No project / No profile
- [ ] My account - Overview | No donation / No project
- [ ] My account - Overview | Has project / Has donations

**Comment by MoeNick** [comment]
- [ ] Toast message for uncompleted profiles while they are viewing my account. 
 When I sign and I don't have a completed profile, now I see this:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/53274c11-078f-422f-8b86-a8846d53925e)

But I was supposed to see this:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/009368a0-8f46-494c-a040-6a1135fd08d8)

**Comment by MoeNick** [comment]
QA points today:

- [ ] 1- Toast on my account, the width of this toast is not fit with the screen 

2- when clicking on complete profile view, it tries to load edit instead of onboarding
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4959cc12-5f7a-4387-9d59-83c51fd4122f)

- [ ] 2- when clicking on let's do it, I can't proceed having this error.

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c687df08-beb1-437f-9e50-6732182bc1fc)

- [ ] 3- when my profile is not completed (name OR email is missing) we should remove the edit profile client.

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c0cce31e-1b25-467c-9d5b-6e5c7fd310ed)

- [ ] 4- (Null problem) when we don't have profile name, we shouldn't show the name in the overview tab and my project tab.

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/5075b4b5-776b-4845-8177-89baec180685)

- [ ] 5- Your profile is incomplete should stick in all tabs.

For example, I can see it in the overview but I can't see it, in my donations.
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e303fa39-0487-4a95-b932-6d4065e16f62)

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/d88fe214-d1d6-4693-96d8-25a334e7c0ef)
