### ISSUE TITLE
Analyze and improve visibility of what's up on Giveth Carousel

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4356]
We should find out how users are using the "What's up on Giveth" Carousel, if it's being clicked on or even viewed by existing, repeat users. 

We should explore options for increasing the visibility of this carousel to inform our existing users of new announcements, features and events that affect them! 

Context: @oyealmond was mentioning to me that we rely too much on twitter to let our community know what's the latest - the result is that our twitter is pushing out too much content and things are getting lost in the noise. We should explore other avenues to get our users attention on the latest happenings on Giveth

![Image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f68e7b27-564b-4b3f-84d6-8a3ab73a10f8)

**Comment by mosaeedi** [comment]
I'll take a look and see what we have on PostHog and GA! Let me review and analyze there, then I'll share the result her

**Comment by mosaeedi** [comment]
**Overall**, it looks like user are noticing this section

### Reports
**1. 30% of users scrolled this far**
<img width="1465" alt="Screenshot 2024-07-11 at 10 57 43 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b66eac8d-be64-4cad-b1ed-cca3285bbdc4">


**2. And here are the mouse movements and clicks over this section**
_It means users are interacting with this section_

**Comment by mosaeedi** [comment]
But in order to get more info, we need to setup some custom events on this section.


1. Explore button
Event: `Giveth news Explore`

<img width="518" alt="Screenshot 2024-07-11 at 11 18 44 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/2e412911-c734-4a8c-b1a9-40cce076eb0e">


2. Using the next button
Event: `Giveth news next slide` 

<img width="475" alt="Screenshot 2024-07-11 at 11 21 01 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/c346b361-ef47-4b85-a7a2-cf0fd02ab5a9">



3. Using the pagination
Event: `Giveth news pagination [pagenumber] `

<img width="474" alt="Screenshot 2024-07-11 at 11 23 24 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b1fec939-4f03-460f-9c0b-ab6e80597731">


---

## Setting up custom events 
For sending custom events -> [Link to PostHog Doc](https://posthog.com/docs/getting-started/send-events#2-capture-custom-events)

**Comment by kkatusic** [comment]
@divine-comedian I like this tool, let you know when I submit PR, hope today ;)


https://github.com/user-attachments/assets/78084db3-a193-4fdf-b760-4b3c158061c4

**Comment by kkatusic** [comment]
@divine-comedian you can test [here](https://giveth-dapps-v2-git-addposthog-givethio.vercel.app/) on staging.

Please let me know if something missing. thx
