### ISSUE TITLE
USD value not showing (GIV donations on Gnosis)

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4370]
USD value is not showing correctly for donations made in GIV on Gnosis chain:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/cac098e6-3be8-42d3-8b08-8f5f9cdd8a64)
https://giveth.io/project/regens-unite?tab=donations

Seems like GIV on OP is fine though:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/c0687c18-3732-428e-ad18-a1f1d3ea68ce)

**Comment by DevFix0512** [comment]
Hello @WhyldWanderer  A support ticket has been opened for you. Kindly Talk to Gnosis Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by WhyldWanderer** [comment]
and update on this @jainkrati?

I have had some reports from users regarding this. 
The QF donations are not showing in the matching because of this bug.

**Comment by divine-comedian** [comment]
> and update on this @jainkrati or @divine-comedian ?
> 
> I have had some reports from users regarding this. The QF donations are not showing in the matching because of this bug.

I didn't even see this one! When you open issues in the future good that you assign me the issue so it pops up in my notifications

**Comment by divine-comedian** [comment]
@RamRamez - can you jump in to look at this bug since Cherik is out this week

**Comment by RamRamez** [comment]
This problem is already solved by @mohammadranjbarz in [this commit](https://github.com/Giveth/impact-graph/commit/48c42d22d99dde30310dcad27c34346640edf136). We were fetching price of GIV token from Subgraph, resulting errors but now we fetch from Coingecko. So the root cause of this problem has been resolved.

For GIV-earth round, we had a total of 53 donations without price, all of them in GIV. I added a script to fetch donations without price from DB and fill prices from Coingecko. This script can be called from AdminJS qfRound history tab (Coingecko rate limit is 5 requests per minute).

All 53 missing price donations are ok now.

![image](https://github.com/user-attachments/assets/2480f3cc-760b-408a-b482-816eaf03f7bb)

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify. GIV donations price on staging should be filled correctly.

**Comment by LatifatAbdullahi** [comment]
On this!

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @RamRamez 

The GIV donation works as expected and the the USD price column is filled correctly.
