### ISSUE TITLE
CELO Alfajores (testnet) - Does not show token balances and can't donate

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4376]
STAGING 
METAMASK

Testing out making donations on Alfajores CELO testnet I have acquired some CELO native tokens on Alfajores however when I connect to the dapp and go to the donate page my balance of celo tokens does not show and I am unable to donate because the dapp does not recognize my balance 

![Image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2c2b332b-eb5b-4dea-93cd-a9c66adc94c9)

**Comment by MohammadPCh** [comment]
@divine-comedian I'm currently working on the new select token modal and will try to address the issue there. Can you wait for a day?

**Comment by MohammadPCh** [comment]
It's working fine for me on the new branch:
<img width="1340" alt="Screenshot 2024-07-04 at 2 16 57 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/5e45450f-cf9c-4de9-b449-0c2e572196ed">
But maybe there is a problem with the token address or symbol because I see an alert beside that:
<img width="340" alt="Screenshot 2024-07-04 at 2 18 22 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/1fbd7263-46b3-4f75-9c48-b22126cb6305">
and also here:
<img width="369" alt="Screenshot 2024-07-04 at 2 18 49 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/5aed3bec-3b7d-4e02-b579-e29a9050fc5f">
if we should change something let me know. we can update the address of the token from admin.
@divine-comedian

**Comment by divine-comedian** [comment]
Thanks @MohammadPCh - I tested today and it looks to be working well - I was able to donate successfully on alfajores, closing this one for now.
