### ISSUE TITLE
Website link on project page is not working correctly

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4381]
When I try to navigate to the 'website' option at the bottom of the project page, it opens the url with "https://giveth.io/project/" in front of the URL.

Example:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/dafba85d-0e6f-41dc-a06d-a92dabcbcc1d)
https://giveth.io/project/la-madriguera

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/402a86b7-d917-4eeb-8289-58dea4a25909)
https://giveth.io/project/greenpill-nigeria-impactprofit

Its possible that it is user error because it doesnt seem to happen on all of the projects, but I thought it was worth investigating

**Comment by kkatusic** [comment]
@WhyldWanderer it was bug, I fixed it, thx

**Comment by divine-comedian** [comment]
@kkatusic - we can safely close this one? It's been fixed on production?

**Comment by kkatusic** [comment]
@divine-comedian who will I tag to test this? thx

**Comment by divine-comedian** [comment]
@LatifatAbdullahi 

## to test 
- add a "website" to the social links for an existing or new project (can be any website on the internet)
- connect with another address that is not project owner
- navigate to public view of project page that has website link added
- verify link works and does not append `https://giveth.io/project/` to the front of the URL 

@kkatusic - when this passes QA we should prepare a hotfix for it, since it is a production bug.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @kkatusic 

**Test Update**

Status: **Test Pass**

This works as expected


Uploading UIProject _ Giveth - Google Chrome 2024-07-23 19-26-50.mp4…
