### ISSUE TITLE
UI issue on My Account/ One-Time Donation

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4586]
As you can see in below pic in donation table QF Round column scroll bar is shown for some QF rounds like "GIV-ARB QF Round"

<img width="1414" alt="Screenshot 2024-08-19 at 9 40 21 AM" src="https://github.com/user-attachments/assets/a181eb24-66f9-4e81-be3b-d08d0ae2ceeb">

https://github.com/user-attachments/assets/530c9345-92b3-4ae7-82db-8348cc6b0b13

cc: @divine-comedian

**Comment by divine-comedian** [comment]
@kkatusic - can you check this out, maybe we should change the behaviour. 

we should change the overflow to prevent the scroll bar from appearing. If information is cut off from the view of the table the entire table should be scrollable horizontally instead of having a scroll bar for each column/cell separately

**Comment by maryjaf** [comment]
![image](https://github.com/user-@kkatusic ttachments/assets/5b615b43-afcc-42d4-a9bf-6748265d4516)
Thanks @kkatusic

**Comment by divine-comedian** [comment]
@maryjaf PS your image link seems to not be formatted correctly :crying_cat_face:
