### ISSUE TITLE
Some fixes for donate page

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#464]
1. add check custom token by backend field `supportCustomTokens`
2. add Switch network to change network modal
3. remove redundant `networksParams`
4. fix showing gemini modal for giv and givingBlock
5. fix showing previous network token list when network is changed and no token on new network
6. fix disabling donate button on zero input amount or no token selected
7. improving donate page styles and code structure
8. fix anonymous donation and remove required sign for them
9. fix donation success view givback learn more link
10. move conditions checks from `DonateModal.tsx` to `CryptoDonation.tsx`
11. removing unused and unnecessary components, vars and styles
12. decompose `DonateIndex.tsx` into smaller React components

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

> 1. add check custom token by backend field `supportCustomTokens`
> 2. add Switch network to change network modal
> 3. remove redundant `networksParams`
> 4. fix showing gemini modal for giv and givingBlock
> 5. fix showing previous network token list when network is changed and no token on new network
> 6. fix disabling donate button on zero input amount or no token selected
> 7. improving donate page styles and code structure
> 8. fix anonymous donation and remove required sign for them
> 9. fix donation success view givback learn more link
> 10. move conditions checks from `DonateModal.tsx` to `CryptoDonation.tsx`
> 11. removing unused and unnecessary components, vars and styles
> 12. decompose `DonateIndex.tsx` into smaller React components

1. checked out adding custom tokens from adminBro from related issue - seems to be working correctly on giveth UI

2. switch network button appears when on wrong network - I am able to exit the modal and remain on the wrong network by click off-screen. the modal dissapears if I click anywhere off the modal - perhaps we shoudln't make it so easy for the users and make them click the `X` only to close the modal since it is important. Also the switch network toggle is very small and only has one option. If we look at a similar function modal in the GIVfarm we can see how we should make the format consistent for switching networks 
![image](https://user-images.githubusercontent.com/67759413/163645580-d3995524-fe6e-47a6-a514-d5b54eedaab9.png)
vs. 
![image](https://user-images.githubusercontent.com/67759413/163646587-4ac83e83-b829-493d-a399-0f2449aac4a8.png)
3. not sure how to test

4. Do you know of a way to test this modal on staging? Since I cannot access mainnet token lists I can't try to donate GIV to a giving block project - also strange thing I noticed is that on the xdai network CRV shows up as the one and only token to donate.

unlike production there is no text telling me I can only donate on mainnet - this is normal?
![image](https://user-images.githubusercontent.com/67759413/163648603-b6be4319-d12a-47e6-bca1-5c31eff67af0.png)
5. this is working 
6. - looks good 
7. - not sure how to test 
8. looks good
9. modal looking good except the colour of the `learn more` button - when unhighlighted it's almost the exact same colour as the background - is there another acceptable colour theme to use? maybe the salmon pink
![image](https://user-images.githubusercontent.com/67759413/163649006-828e39b6-7230-4379-9b69-dd0a214fce3d.png)

10,11,12 - not sure how to test! 

here ya go!
