### ISSUE TITLE
Update CMC Total supply & circulating supply

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4677]
### Coingecko:
Circulating + Total Supplies: https://circulating.giveth.io/token-supply

### Coinmarketcap:
Circulating Supply: https://supply.giveth.io/giv-supply-cmc?q=circulating
Total Supply: https://supply.giveth.io/giv-supply-cmc?q=totalcoins

**Comment by laurenluz** [comment]
@wmb81321 please update here once this is fixed on CMC 

cc @geleeroyale

**Comment by wmb81321** [comment]
The request we made using SRD of CMC was approved, but circulating supply still having some issues. 

Looks like we have to move with a form to VERIFY OUR circulating Supply, I created this issue on notion to keep this process on track: https://www.notion.so/giveth/Updating-Total-and-Circulating-supply-CoinmarketCap-6b89acf02f704173b481bc2e96b9318f

![Screenshot 2024-09-04 at 09 33 13](https://github.com/user-attachments/assets/e842e3f0-6cab-4edc-8b1b-4b825551f94f)

**Comment by laurenluz** [comment]
thank you for pushing on this @wmb81321! Keep me posted!

**Comment by mhmdksh** [comment]
@laurenluz I'm mentioning myself here as I would like to be informed if there was any updates or modifications needed on this since I worked on the endpoints

**Comment by wmb81321** [comment]
@aminlatifi @mhmdksh I noticed the circulating Supply from the API and the Dunedashboard are diferent. Also I got a Different number when I aggregate the list of GIV non-circulating supply. You can find them in the tab called "GIV Circulating Supply" on [GIV Distro audit](https://docs.google.com/spreadsheets/d/17MzotVIFaAHLwzUZPHvIHuXfgA0jks9xUlDZWwiH0n8/edit?gid=1490149520#gid=1490149520)

<img width="685" alt="Screenshot 2024-10-18 at 4 19 05 PM" src="https://github.com/user-attachments/assets/ad22817a-290c-4a5d-8fee-764d8e227ec5">

This is the _**list of Non Circulating Supply contracts**_, some contracts are missing on the **_Dune dashboard Querys_** and some other on the [GIV circulating Supply endpoint](https://github.com/Giveth/giv-supply-function)

<img width="1079" alt="Screenshot 2024-10-18 at 4 21 41 PM" src="https://github.com/user-attachments/assets/c29d90e4-3a6f-461a-a831-985fa3d3de8e">

**Comment by aminlatifi** [comment]
@wmb81321 Can you specify issues one by one please, then we can walk through them and fix if there is any issue in either Dune or API

**Comment by wmb81321** [comment]
@aminlatifi, thank you for fixing the DuneDashboard queries. This message summarizes our discussion from the Discord chat. I hope this breakdown helps clarify things.

## DuneDashboard Queries ✅ - @aminlatifi 
The following addresses have already been added to the DuneDashboard queries to build the GIV Circ Supply:

**Gnosis**
- nrGIV Multisig | [0x0018C6413BFE5430ff9ba4bD7ac3B6AA89BEBD9b](https://gnosisscan.io/address/0x0018C6413BFE5430ff9ba4bD7ac3B6AA89BEBD9b)

**Polygon ZKEVM:**
- Token Distribution | [0x4fB9B10ECDe1b048DBC79aBEAB3793edc93a0d54](https://zkevm.polygonscan.com/address/0x4fB9B10ECDe1b048DBC79aBEAB3793edc93a0d54)
- Giveth Multisign | [0xaF4D68B8084b01D2c8120120497511035A2ea3a1](https://zkevm.polygonscan.com/address/0xaF4D68B8084b01D2c8120120497511035A2ea3a1)
- Multisig Liquidity | [0xa1769a425EA1197f32d8C3e0fbE3F92EaDACC21A](https://zkevm.polygonscan.com/address/0xa1769a425EA1197f32d8C3e0fbE3F92EaDACC21A)

## GitHub GIV Supply Function - @MoeNick 🟦
We have a repository for the [GIV Circulating Supply Endpoint](https://github.com/Giveth/giv-supply-function). The following addresses have to be excluded of the GIV Circulating Supply because they are excluded on out the [Dune dashboard GIVeconomy](https://dune.com/giveconomy/giveconomy):

**Mainnet**
_Currenlty, these addresses are not holding GIV, but They are bridges that we are excluding from GIV circulating supply in our DuneDashboard queries:_
- Gnosis OmniBridge | [0x88ad09518695c6c3712ac10a214be5109a655671](https://etherscan.io/address/0x88ad09518695c6c3712ac10a214be5109a655671)
- Optimism Gateway | [0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1](https://etherscan.io/address/0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1)
- Polygon ZKEVM Bridge | [0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe](https://etherscan.io/address/0x2a3DD3EB832aF982ec71669E178424b10Dca2EDe)

**Optimism**
_I believe this is the bridge used to connect to Solana. It holds approximately 3.7 million GIV:_
- Wormhole Bridge | [0x1D68124e65faFC907325e3EDbF8c4d84499DAa8b](https://etherscan.io/address/0x1D68124e65faFC907325e3EDbF8c4d84499DAa8b)

**Polygon ZKEVM** 
_Currently, we are facing an issue regarding this one. This addreses hold almost 9 Million GIV.
- Token Distribution | [0x4fB9B10ECDe1b048DBC79aBEAB3793edc93a0d54](https://zkevm.polygonscan.com/address/0x4fB9B10ECDe1b048DBC79aBEAB3793edc93a0d54)
- Giveth Multisign | [0xaF4D68B8084b01D2c8120120497511035A2ea3a1](https://zkevm.polygonscan.com/address/0xaF4D68B8084b01D2c8120120497511035A2ea3a1)
- Multisig Liquidity | [0xa1769a425EA1197f32d8C3e0fbE3F92EaDACC21A](https://zkevm.polygonscan.com/address/0xa1769a425EA1197f32d8C3e0fbE3F92EaDACC21A)

**Comment by mhmdksh** [comment]
Thanks for reviewing this @wmb81321 

I have checked the code, these addresses are not in the endpoints that is run by this repo https://github.com/Giveth/giv-supply-function

@aminlatifi These should be different right??

**Comment by aminlatifi** [comment]
> Thanks for reviewing this @wmb81321
> 
> I have checked the code, these addresses are not in the endpoints that is run by this repo https://github.com/Giveth/giv-supply-function
> 
> @aminlatifi These should be different right??

I think they must be in harmony, anything is excluded from circulating supply for instance must be excluded there as well. @laurenluz do you confirm?

**Comment by mhmdksh** [comment]
@wmb81321 I think the Solana Addresses are still missing, as I see my endpoint and the Dune Dashboards don't match 100%

**Comment by wmb81321** [comment]
> Coingecko: http://80.240.30.129:3000/token-supply
> Coinmarketcap: http://80.240.30.129:3000/giv-supply-cmc?q=circulating

@MoeNick yep, these Endpoints are matching with GIVeconomy Dune dashboard and contracts. 

As of 23/10/2024 16:00 UTC, the Circ Supply is 276,200,730 GIV

**Comment by mhmdksh** [comment]
@wmb81321 The new fix has been pushed and the official links are updated here:

- https://circulating.giveth.io/token-supply
- https://supply.giveth.io/giv-supply-cmc?q=circulating

Let me know if all is good now :)
