### ISSUE TITLE
Technical Analysis - Discuss idagram and docs

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#496]

**Comment by CarlosQ96** [comment]
We should add on top a rate limit.

**Comment by CarlosQ96** [comment]
We should add versioning on top. Since now other companies will use our API, if we add version changes we might break their app.

**Comment by CarlosQ96** [comment]
I am concerned with the registration flow. I think we should:
1. Have a form organizations can fill with their emails and description, mision and why they want to use our api. 
2. This would create a record in a table where an admin can approve or contact further the organization with their provided email. (set scopes, etc)
3. If everything is alright, we proceed to create a clientId and send back to the organization email the info encrypted. With their available scopes and api docs. (the givingblocks does something cool like this sending all encrypted).
4. Like you wrote, third parties would request an access token with the scopes they want to use. This would generate one with an expiration. (Must be a POST request, no GET because GET requests cache params)
5. We would do a refresh endpoint, that also requires the clientId.

I think everything else you listed is good! Logs is a really good idea that must be implemented early so we avoid pain points later.

**Comment by mohammadranjbarz** [comment]
> I am concerned with the registration flow. I think we should:
> 
> 1. Have a form organizations can fill with their emails and description, mision and why they want to use our api.
> 2. This would create a record in a table where an admin can approve or contact further the organization with their provided email. (set scopes, etc)
> 3. If everything is alright, we proceed to create a clientId and send back to the organization email the info encrypted. With their available scopes and api docs. (the givingblocks does something cool like this sending all encrypted).
> 4. Like you wrote, third parties would request an access token with the scopes they want to use. This would generate one with an expiration. (Must be a POST request, no GET because GET requests cache params)
> 5. We would do a refresh endpoint. This checks if the token is not revoked.
> 
> I think everything else you listed is good! Logs is a really good idea that must be implemented early so we avoid pain points later.
> 
> My last questions would be: Should tokens be infinitely refreshable? should we set a second expiration where they have to request a new one after say 30 days? Should they send the clientId again for refreshing?

Thanks for sharing your ideas, 
I agree with what you said, but just one thing currently we don't send emails directly from our backend ( All emails go through auto pilot), so we need to
**Use an email service in our backend**

About expiration, these two approaches came to my mind
1. Organization request to our server (with their apiKey) and we generate (`accessToken` + `refreshToken`) for them, usually `accessToken` has very short lifeTime something like `2 hours`, and ‍‍ `refreshToken` has longer lifeTime something like `30 days`, so when their accessToken got expired they call webService to get new tokens ( this time with their `refreshToken` NOT their apiKey) , and get new accessTokens

2. They can just call with their apiKey and get accessToken with limited lifeTime, if it got expired they can get new one

**PS** Obviously the second one is simpler to implement

![al pacino](https://user-images.githubusercontent.com/9850545/163326680-466b3781-0f4c-4805-9a63-d8c3b98ab0d9.jpeg)

Just Kidding

**Comment by CarlosQ96** [comment]
Hahaha nice one. We kinda know the right answer always but actively avoid it for simpler implementation 🤣

**Comment by MoeNick** [comment]
Let's do it Guys :)

**Comment by MoeNick** [comment]
Any update on this @mohammadranjbarz @CarlosQ96 ?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
https://github.com/Giveth/apiGive/blob/main/diagrams/main_flow.md

This is the last updated diagram that is synced with what I implemented

**Comment by MoeNick** [comment]
@CarlosQ96 I need your confirmation to move it to done.

**Comment by CarlosQ96** [comment]
@MoeNick we can move it to done. Mohammad has done a great job.

**Comment by MoeNick** [comment]
@Cotabe just for you information for APIGIV docs

**Comment by Cotabe** [comment]
Thanks!!! amazing work guys!!!
