### ISSUE TITLE
Add CR Coin to Accepted Token List

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapps-v2#537]
Please add CR Coin - contract https://etherscan.io/token/0xfb19c03a02a519a44542343803f3d42578cbc243 - to the list of tokens that can be received for GIVbacks to facilitate donations being offered in CR Coin for some projects on Giveth.

**Comment by laurenluz** [comment]
@Danibelle As per our decided process, before we add a new token to the list, it should be posted as a request on the [Giveth Forum GIVbacks token list post](https://forum.giveth.io/t/givbacks-token-list/253)

We didn't fully decide exactly if a snapshot vote would be needed or not, but at the very least I think we should bring it up in the governance call before proceeding.

**Comment by Danibelle** [comment]
ahh yes, I was looking for where that was discussed.. thanks @laurenluz !

**Comment by MoeNick** [comment]
@laurenluz @Danibelle 
According to our latest change, Admin can add a token to the default list and set the GIVback eligibility true OR false. 
So in this case, the user can search for the non-eligible token instead of getting obliged to paste the address. So it can be searched, and selected and the yellow toast message will be shown and tell the user this token is not eligible with a hyperlink to the forum post. 

So you may want to list them on the DApp in the default token list to let the giver know it's not eligible. 

P.S: right now all accepted tokens are GIVback=True.
