### ISSUE TITLE
Tnx is not completed but it says Tnx submitted

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#538]
You can test it by choosing very low gas fees, then your tnx will be queued in your wallet and you can even cancel it, but the app says "You're eligible for Givback"

![image](https://user-images.githubusercontent.com/73441857/163825878-b8aeb761-f575-40a4-aeef-da1fdea0e541.png)

**Comment by RamRamez** [comment]
I even received emails for my (not confirmed) donations

![image](https://user-images.githubusercontent.com/73441857/163827637-6abc28bb-253d-48f7-a38d-90b7ecbdf764.png)

**Comment by MoeNick** [comment]
Thanks, @RamRamez for reporting.
@mohammadranjbarz @CarlosQ96 do you have any idea?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Creating donation doesnt have any validation with blockchain network, so you can create donations as many as you want ( and users can make our donation leaderboard messy)
but we have a job later that check donation's transaction in network, and if they really happened we change the status of donation to `verified` ( when creating donation it's `pending`)  and just `verified` donations are givback eligible 

@MoeNick if you want to we can change to flow, for instance we can send email to project owners / donors just when we verified the donation, or just showing `verified` donations in project page, 
I think first of all it's a business decision ( because when verifying donations I changed in some way to not affect UX because it was business decision), and after that we can talk about technical problems, we can have short talk about this topic if you want to

**Comment by MoeNick** [comment]
@mohammadranjbarz I think it's time to revise it. let's send the email after they got verified.

**Comment by mohammadranjbarz** [comment]
Yeah we did that in this PR
https://github.com/Giveth/impact-graph/pull/507#issuecomment-1122213062

**Comment by divine-comedian** [comment]
tested this in issue #693 

can confirm while tx is still pending no email is sent, once it is verified the email is sent

moving to DONE
