### ISSUE TITLE
View Similar Projects link on project pages

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#569]
In clicking "View Similar Projects", it leads to the main [Project page](https://giveth-dapps-v2.vercel.app/projects). I'm wondering if shouldn't it be more specific to "related projects" or at least projects in a related/same category? 

For example, [this page](https://giveth-dapps-v2.vercel.app/project/eyebeam) is under the category The Giving Block, but once I click on "View Similar Projects", it doesn't lead to The Giving Block category but to the main Project Page. 
 
![image](https://user-images.githubusercontent.com/93360299/164245790-409b829d-df42-4c68-ae12-ac3766edf13b.png)

@MoeNick

**Comment by MoeNick** [comment]
It's under construction :)

**Comment by MoeNick** [comment]
Test Scenario:  for GivingBlocks projects, you should not see any related projects at all. @missgene

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

currently this feature does not appear to be working at all, clicking `view similar projects` on any project, giving block or otherwise will simply lead us back to this URL.

![image](https://user-images.githubusercontent.com/67759413/169869094-dbf6c24a-1600-4238-950e-8ca6f4a13edc.png)




> GivingBlocks

in this scenario maybe we should see other giving block projects?

**Comment by MoeNick** [comment]
It should link to a bookmarked section in the page.
