### ISSUE TITLE
Get Giveth's farm listed on defi llama

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#744]
https://docs.llama.fi/list-your-project/submit-a-project

Defi llama has become one of the best places to find yields... we should get Giveth on there to drive adoption... 

Our pools would actually do well on here, we have amazing APRs relative to other projects.

<img width="1239" alt="Screen Shot 2022-05-18 at 1 42 30 PM" src="https://user-images.githubusercontent.com/14945613/169142880-383afc22-f41a-4c35-ba26-044c01ed0ec0.png">

**Comment by GriffGreen** [comment]
another link: https://github.com/DefiLlama/yield-server#readme

**Comment by MoeNick** [comment]
Is there any progress dudes?

**Comment by CarlosQ96** [comment]
@MoeNick Consulting with @aminlatifi what would be the best way.
Would it be per yield farm the integration or just once per token/service?

We mostly need this data:
```
{
    pool: "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae90xb53c1a33016b2dc2ff3653530bff1848a515c8c5", // unique identifier for the pool
    chain: "Ethereum", // chain where the pool is
    project: 'aave', // protocol (using the slug again)
    symbol: "USDT", // symbol of the tokens in pool, can be a single symbol if pool is single-sided or multiple symbols (eg: USDT-ETH) if it's an LP
    tvlUsd: 1000.1, // number representing current USD TVL in pool
    apy: 1.2, // current APY of the pool in %
  };
```

and write an adapter similar to this:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/92376054/172189077-3ae47aa5-5e46-4d8f-84dd-68c1101416b8.png">

**Comment by aminlatifi** [comment]
Most of our pools (uniswapv2, sushi, honeyswap) are based on uniswapv2. So the logic for them will be the same. The exception can be balancer, but that will not be an issue because almost all of the logic has been implemented before.
Essential values can be fetched from subgraph like [here](https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2/graphql?query=%0A++++%23%0A++++%23+Welcome+to+The+GraphiQL%0A++++%23%0A++++%23+GraphiQL+is+an+in-browser+tool+for+writing%2C+validating%2C+and%0A++++%23+testing+GraphQL+queries.%0A++++%23%0A++++%23+Type+queries+into+this+side+of+the+screen%2C+and+you+will+see+intelligent%0A++++%23+typeaheads+aware+of+the+current+GraphQL+type+schema+and+live+syntax+and%0A++++%23+validation+errors+highlighted+within+the+text.%0A++++%23%0A++++%23+GraphQL+queries+typically+start+with+a+%22%7B%22+character.+Lines+that+start%0A++++%23+with+a+%23+are+ignored.%0A++++%23%0A++++%23+An+example+GraphQL+query+might+look+like%3A%0A++++%23%0A++++%23+++++%7B%0A++++%23+++++++field%28arg%3A+%22value%22%29+%7B%0A++++%23+++++++++subField%0A++++%23+++++++%7D%0A++++%23+++++%7D%0A++++%23%0A++++%23+Keyboard+shortcuts%3A%0A++++%23%0A++++%23++Prettify+Query%3A++Shift-Ctrl-P+%28or+press+the+prettify+button+above%29%0A++++%23%0A++++%23+++++Merge+Query%3A++Shift-Ctrl-M+%28or+press+the+merge+button+above%29%0A++++%23%0A++++%23+++++++Run+Query%3A++Ctrl-Enter+%28or+press+the+play+button+above%29%0A++++%23%0A++++%23+++Auto+Complete%3A++Ctrl-Space+%28or+just+start+typing%29%0A++++%23%0A++%7B%0A++++pair%28id%3A%220xbeba1666c62c65e58770376de332891b09461eeb%22%29+%7B%0A++++++reserveUSD%0A++++++reserve0%0A++++++reserve1%0A++++++token0+%7B%0A++++++++symbol%0A++++++%7D%0A++++++token1+%7B%0A++++++++symbol%0A++++++%7D%0A++++%7D%0A++%7D)

Values like reward rate also can be fetched from our own subgraph like [here](https://api.thegraph.com/subgraphs/name/aminlatifi/giveth-economy-xdai/graphql?query=%0A++++%23%0A++++%23+Welcome+to+The+GraphiQL%0A++++%23%0A++++%23+GraphiQL+is+an+in-browser+tool+for+writing%2C+validating%2C+and%0A++++%23+testing+GraphQL+queries.%0A++++%23%0A++++%23+Type+queries+into+this+side+of+the+screen%2C+and+you+will+see+intelligent%0A++++%23+typeaheads+aware+of+the+current+GraphQL+type+schema+and+live+syntax+and%0A++++%23+validation+errors+highlighted+within+the+text.%0A++++%23%0A++++%23+GraphQL+queries+typically+start+with+a+%22%7B%22+character.+Lines+that+start%0A++++%23+with+a+%23+are+ignored.%0A++++%23%0A++++%23+An+example+GraphQL+query+might+look+like%3A%0A++++%23%0A++++%23+++++%7B%0A++++%23+++++++field%28arg%3A+%22value%22%29+%7B%0A++++%23+++++++++subField%0A++++%23+++++++%7D%0A++++%23+++++%7D%0A++++%23%0A++++%23+Keyboard+shortcuts%3A%0A++++%23%0A++++%23++Prettify+Query%3A++Shift-Ctrl-P+%28or+press+the+prettify+button+above%29%0A++++%23%0A++++%23+++++Merge+Query%3A++Shift-Ctrl-M+%28or+press+the+merge+button+above%29%0A++++%23%0A++++%23+++++++Run+Query%3A++Ctrl-Enter+%28or+press+the+play+button+above%29%0A++++%23%0A++++%23+++Auto+Complete%3A++Ctrl-Space+%28or+just+start+typing%29%0A++++%23%0A++%7B%0A++++unipoolContractInfos%28first%3A1%29+%7B%0A++++++id%0A++++++rewardRate%0A++++%7D%0A++%7D)

The APR calculation are already implemented in the frontend.
https://github.com/Giveth/giveth-dapps-v2/blob/8d896f84989d55b3ee49c96804ad395942884079/src/lib/stakingPool.ts#L168
https://github.com/Giveth/giveth-dapps-v2/blob/8d896f84989d55b3ee49c96804ad395942884079/src/lib/stakingPool.ts#L86

**Comment by CarlosQ96** [comment]
This is my forked Repo: https://github.com/CarlosQ96/yield-server/tree/giveth_farms_adapter

**Comment by CarlosQ96** [comment]
Location: 
src/adaptors/giveth/index.js

Node version used: 
16.42.2

Install dependencies: 
npm install

To test cmd: 
node src/adaptors/test.js src/adaptors/giveth/index.js

**Comment by CarlosQ96** [comment]
PR of the Fork: https://github.com/CarlosQ96/yield-server/pull/1

**Comment by CarlosQ96** [comment]
Data is from production

**Comment by CarlosQ96** [comment]
@divine-comedian testerMaster64

**Comment by divine-comedian** [comment]
@CarlosQ96 testing this out locally, I cloned the repo, switched to node 16, installed the dependencies then ran the command in my terminal from the yield-server folder.

I received this error:

```
(base) motch@apples-MBP yield-server % node src/adaptors/test.js src/adaptors/giveth/index.js
==== Testing src/adaptors/giveth/index.js ====
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/motch/Desktop/github/yield-server/src/adaptors/giveth/index.js'
Require stack:
- /Users/motch/Desktop/github/yield-server/src/adaptors/test.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/motch/Desktop/github/yield-server/src/adaptors/test.js:22:18
    at Object.<anonymous> (/Users/motch/Desktop/github/yield-server/src/adaptors/test.js:54:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/motch/Desktop/github/yield-server/src/adaptors/test.js' ]
}
(base) motch@apples-MBP yield-server % nvm -v
0.39.1
(base) motch@apples-MBP yield-server % node -v
v16.15.1
(base) motch@apples-MBP yield-server % 
```

**Comment by CarlosQ96** [comment]
Switch to the branch giveth_farms_adapter

**Comment by divine-comedian** [comment]
looks to be working!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182217020-f39d8136-ac38-40c9-a0da-82024e5da093.png">

However I do see a few mistakes.

Notably we're missing two farms:
GIV/WETH (Sushiswap) on Gnosis Chain:
https://blockscout.com/xdai/mainnet/address/0xfB429010C1e9D08B7347F968a7d88f0207807EF0

GIV/ETH (Balancer) on Mainnet:
(https://etherscan.io/address/0x7819f1532c49388106f7762328c51ee70edd134c)

I also noticed that the single asset GIV pools on mainnet and gnosis chain have their usdValue in WEI while the LP pools are in regular amounts.

**Comment by CarlosQ96** [comment]
@divine-comedian thanks! For sushiswap and balancer getting all the info from the subgraph is not simple. We decided to start with these 4 farms only.

**Comment by CarlosQ96** [comment]
Also on the APR I noticed we calculate it by multiplying the seconds in a year. So perhaps in this case APR and APY are the same?

**Comment by aminlatifi** [comment]
> @divine-comedian thanks! For sushiswap and balancer getting all the info from the subgraph is not simple. We decided to start with these 4 farms only.

@CarlosQ96 Is not possible to query web3 there?

**Comment by aminlatifi** [comment]
> > @divine-comedian thanks! For sushiswap and balancer getting all the info from the subgraph is not simple. We decided to start with these 4 farms only.
> 
> @CarlosQ96 Is not possible to query web3 there?
@CarlosQ96 For sushi xdai-weth on xdai network we have this info available by subgraph https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-xdai

```
{
  pair(id: "0x55ff0cef43f0df88226e9d87d09fa036017f5586") {
    token0
    token1
    reserve0
    reserve1
  }
}
```
إخق

**Comment by divine-comedian** [comment]
We should consider that in as little as 3 weeks the GIVfarm could change drastically. 

We will see the end of GIV staking on mainnet

The GIV-DAI and GIV-xDAI farms will probably end as well. This would leave us with only the GIV/ETH farms (balancer, sushiswap), GIVpower (GIV staking on Gnosis Chain) and the angel vault.

So if we're going to put the work into this hopefully we find something that stays relevant for longer than 3 weeks.

**Comment by aminlatifi** [comment]
> We should consider that in as little as 3 weeks the GIVfarm could change drastically.
> 
> We will see the end of GIV staking on mainnet
> 
> The GIV-DAI and GIV-xDAI farms will probably end as well. This would leave us with only the GIV/ETH farms (balancer, sushiswap), GIVpower (GIV staking on Gnosis Chain) and the angel vault.
> 
> So if we're going to put the work into this hopefully we find something that stays relevant for longer than 3 weeks.

Good point, angel vault APR is implemented as well in the UI. The farm will start this Thursday and we can check our implementation correctness on this repo.

**Comment by CarlosQ96** [comment]
Ok so I should remove Giv-Dai, Giv-xDai, and add sushiswap + angel vault, instead.

**Comment by divine-comedian** [comment]
> Ok so I should remove Giv-Dai, Giv-xDai, and add sushiswap + angel vault, instead.

The GIV/DAI and GIV/xDAI farms haven't officially been terminated so keep that code stashed somewhere, just in case. 

It will be super important to have sushiswap, angel vault and balancer in addition to GIVpower.

I can see a few different balancer pools listed on defillama, for example:
https://defillama.com/yields/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014

maybe before breaking your head we could reach out to @mendesfabio who might know how balancer does it?

**Comment by divine-comedian** [comment]
Looks like ICHI also took a stab at trying to list their angel vault on the platform, not sure if it's working however
https://defillama.com/yields/pool/0x9e200055592f345743ae7450756700d424f302e9

**Comment by mendesfabio** [comment]
Balancer would be similar to Uniswap, but you should consider the token weights. The query you will make is basically this:

```
{
  pool(id: "<PLACEHOLDER>") {
    id
    tokens {
      id
      balance
      weight
    }
    totalShares
  }
}
```

`totalShares` is the same as `totalSupply` and `balance` is the same as `reserve` -- compared to the Uniswap schema.

Note that Balancer's Subgraph is actually at https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-v2. Amin has sent the V1 link.

**Comment by divine-comedian** [comment]
moving this back to sprint backlog for now

**Comment by mateodaza** [comment]
Created a new [PR](https://github.com/CarlosQ96/yield-server/pull/2) removing deprecated farms and adding missing ones

@CarlosQ96 @MohammadPCh @divine-comedian

**Comment by mateodaza** [comment]
Waiting this [PR](https://github.com/DefiLlama/defillama-server/pull/851) for us to be listed on defi llama. After that I'll leave another PR for setting the adapter

**Comment by mateodaza** [comment]
We're live! 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18689480/189672649-2431878e-3679-4efc-86bd-6c2666c0d364.png">

You gotta toggle the staking and pool2 options to show all the values, the reasoning for that it's explained [here](https://github.com/DefiLlama/DefiLlama-Adapters/discussions/438)

**Comment by mateodaza** [comment]
Also, found out we can make this work for DefiPulse as well
![image](https://user-images.githubusercontent.com/18689480/189677757-f44c8c53-d099-454d-b390-4283687e12b6.png)

Should we do it? I think we should! @MoeNick @GriffGreen @divine-comedian

**Comment by CarlosQ96** [comment]
Imo, if we want the coin more visible and go up we should!
