### ISSUE TITLE
RegenFarms - Show all farms, regardless of connected chain.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#821]
Currently with the launch of CULT/ETH we will have two regen farms, on two chains. 

When we are connected to a chain other than Kovan or xDAI only the regen farm on Kovan is shown. 

Suggesting we show all regenfarms at once, however if the user is not connected to the right chain we show the blurred out card and the modal to switch networks. Like this as a suggestion:

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/4b2e1409-0eb5-4874-8ddb-45545968e711)

This allows the user to see all the regen opportunities and be aware of them, no matter what chain they are on.

WDYT @markoprljic @mateodaza ?

**Comment by markoprljic** [comment]
Yes, this sounds reasonable to do. 
In case of many farms on different chains (since these cards a quite big), we could show a message below "There are 6 more farms on other networks. Polygon (2) Farm 1, Farm 2, Switch to Polygon. Gnosis (4) Farm 1,23456 Switch to Gnosis"

One thing unrelated to this issue, it would be good to include number of farms on network switch at the top of the page.
Gnosis (3), Ethereum (3)

<img width="449" alt="Screenshot 2022-05-28 at 17 17 15" src="https://user-images.githubusercontent.com/5704285/170831533-4d25f19e-6c2f-42c2-9908-264ffdd1a710.png">

**Comment by laurenluz** [comment]
+1 on this. @MoeNick - not necessary before we launch CULT farm, but would love to see this in the upcoming sprints :)
