### ISSUE TITLE
Create / Edit  Projects: Frontend to use new mutuation

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#899]
As a project owner, I want to have multi-recipient addresses for every network, while I'm on create a project or when I want to edit my project. 

Figma Design:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=5790%3A126811

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/899?planning-poker) with ZenHub @mateodaza

**Comment by MoeNick** [comment]
Hey, According to this design:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/da25fef3-f8cc-453e-90aa-19088201ff4b)

There are these scenarios here:
1- The User has 2  addresses for each network.
2- The user has only one address and wants to raise funds only in 1 network.
3- The User has only one address but it's okay to raise funds with this address to another network. 

So, the current UX makes both addresses required, so for #1 user types above, for the #2 user types, and #3 user types, I think the UX is confusing. 

I suggest: 
1- we add a checkbox on top of each input, asking the user: _"I want to raise funds in Ethereum Main-Net"_ OR _"I want to raise funds in Gnosis"_
when it's clicked user has to put the address. 
2- an option to let the user add _"The same address above"_ for type #3 users (which are okay to use the same address for 2 networks) 
What do you think @mosaeedi @markoprljic

**Comment by markoprljic** [comment]
@MoeNick Please remind me what was the policy we implemented for allowing project owner to select a different receiving address?
I do recall we had some conversations around that, it's a bit foggy to me but I think there was a use case for that where we made the decision to allow it. Maybe @WhyldWanderer or @laurenluz can help refresh our memory here?

I'd love to see user define their wallet address under their Account (Edit profile), we can even upgrade the My account / Profile page with more settings for user to change. 

This issue is related to Account and Wallet relation issue, I think it has some dependencies and we should probably look at it again after we decide how to deal with the Account and Wallet relation first.

**Comment by MoeNick** [comment]
on Testing:

- [ ] Instead of Primary address, we should write Ethereum mainnet. 
- [ ] ENS checking should be made only in Ethereum main net address field, 
- [ ] ENS checking should be made regardless of which network user is on it right now.
