### ISSUE TITLE
Create a Project - Hyperlink "Browse examples." is not Working/Opening 

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#970]
**Issue :** When Creating a Project and trying to use Hyperlink "Browse examples.", it is not Working or Opening the Projects Page. 

**Steps to Repro :**
1.	Create a Project
2.	Click on the Hyperlink – “how to write a great project description”
3.	Click on "Browse examples."

**Results :** Link is not opening.

**Snapshot for Reference :**

![image](https://user-images.githubusercontent.com/107279959/174902190-93ab5f6e-8234-47cc-8d4f-9f348e2aa38e.png)

**Comment by jeevanplus007** [comment]
@RamRamez  - Make sure it is adding in a NEW TAB

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

creating a new project and looking at the `browse examples` link it now successfully opens `https://staging.giveth.io/projects` in a new tab.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/179581163-e4ca7a64-12a4-4c9e-854f-a5902b2a36f9.png">


this issue seems to be resolved! moving to DONE
